### ISSUE TITLE
ProFTP spamming DBUS

### ISSUE THREAD

**Issue by studidilio** [proftpd/proftpd#818] opened 2019-07-22 10:40 UTC
I have noticed dbus running at high CPU (~90%) on a system with proftp installed. On checking dbus-monitor I can see that there are a very large number of messages being published where a dynamic user is being looked up. A single login seems to be generating 100s of these at a time.

Is the sheer number of these expected and/or is there a way to reduce the count?

ProFTP version 1.3.5e and using mod_sql running on Ubuntu (installed via apt)

**Comment by Castaglia** [comment] 2019-10-12 20:57
Newer versions of ProFTPD try to cache their user/group lookups in memory; you might try a later version of ProFTPD, to see if this behavior still bothers dbus.

**Comment by Castaglia** [comment] 2021-03-11 03:45
It's also possible that these DBUS messages are caused by use of PAM modules; without seeing the full configuration of the ProFTPD installation in question, it's hard to say.

Given the lack of additional details, and age of this ticket, I'll close it.  We can open another ticket with details, if this comes up again.

**Closed by Castaglia** 2021-03-11 03:45 UTC
