### ISSUE TITLE
Consider to replace libsys-hostaddr-perl in test suite

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1039] opened 2020-06-20 10:59 UTC
When running the proftp test suite I noticed that it uses the per module `libsys-hostaddr-perl`. That module is not part of the Debian distribution, hence I [started packaging it](https://bugs.debian.org/955496). In the bug a discussion was opened and some arguments were raised against packaging that module:

- has seen no updates since 2014
- relies on a long-deprecated interface, via a tool that hasn't seen an upstream release since April 2001
- has non-working support for IPv6
- its support for IPv4 isn't stellar either
- doesn't handle lack of answer or answers it doesn't understand
- provides only partial answers

See [E-Mail](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955496#10) for details. Hence I'll refrain from packaging that module. Therefore we still can't run the test suite in Debian distribution.
Consider stop using that module, instead use a different module. No, I didn't look for alternative code yet. If you need me to do that, please call back.

Many Thanks!

**Comment by Castaglia** [comment] 2020-07-18 18:53
Since the issues cited have not caused any issues for the ProFTPD regression test suite, I don't feel they are reasons to _not_ use the module.  If the issue is then one of packaging, I'm more than happy to simply include a local copy of that code in the regression test suite.

**Comment by hpreusse** [comment] 2020-08-02 21:40
If you would do this for us (include a local copy), I'd very thankful. Hilmar

**Comment by Castaglia** [comment] 2021-04-10 23:32
I _may_ be able to use the [`Net::Address::IP::Local`](https://metacpan.org/pod/Net::Address::IP::Local) perl module, via _e.g._ the libnet-address-ip-local-perl package.  Would that also work for you?

**Comment by hpreusse** [comment] 2021-04-11 12:43
> I _may_ be able to use the [`Net::Address::IP::Local`](https://metacpan.org/pod/Net::Address::IP::Local) perl module, via _e.g._ the `libnet-address-ip-local-perl` package. Would that also work for you?

I guess it will. At least the perl module is already present in Debian. Many thanks!

**Comment by Castaglia** [comment] 2021-04-11 13:27
Now fixed in master.  Thanks!

**Closed by Castaglia** 2021-04-11 13:27 UTC
Labels: test
