### ISSUE TITLE
Proftpd as non root on RHEL8 : Error loading module ‘mod_sql_mysql.c’

### ISSUE THREAD

**Issue by Shailendranjain** [proftpd/proftpd#1395] opened 2022-02-14 20:49 UTC
### What I Did

Built proftpd 1.3.7c and ran as non root user on RHEL8 as below

proftpd -c proftpd.conf -nd10

However it failed to run with the below errors

Unable to dlopen ‘mod_sql_mysql.c’: file not found (No such file or directory)
Unable to load ‘mod_sql_mysql.c’; check to see if /car/opt/proftpd/usr/libexec/proftpd/mod_sql_mysql.la’ exists
defaulting to ‘self’ for symbol resolution 
unable to find module symbol ‘sql_mysql_module’ in ‘self’
fatal: LoadModule: error loading module ‘mod_sql_mysql.c’: No such file or directory on line 66 of proftpd.conf

### What I Expected/Wanted

Proftpd should have run successfully as a non-root on RHEL8 
 
 Note: Proftpd runs successfully as a root user on RHEL8.
Also proftpd runs successfully as a non root user on RHEL6

### ProFTPD Version and Configuration

Version used : 1.3.7c ( on RHEL 8 )

Found the same issue with version 1.3.6c on RHEL8

Note: Since the same proftpd.conf works in RHEL6 as a non root ( but not in RHEL 8), did not attach proftpd.conf

**Comment by Castaglia** [comment] 2022-02-14 22:29
Did you compile/install ProFTPD from source, or install via package?  I ask because ProFTPD's running as non-root depends on the ProFTPD configuration (which isn't provided here), so I don't have enough information to try to reproduce this behavior locally.

**Comment by Shailendranjain** [comment] 2022-02-16 20:09
Could this be due to permission set on libcrypto and libssl for RHEL8?

This issue exists only when running as non root user on RHEL8.

Also this issue does not exist when running proftpd as root user.

**Comment by Castaglia** [comment] 2022-02-19 17:12
The crypto libraries used by the MySQL client libraries may be statically linked by the MySQL client library; that library is outside of ProFTPD.

If you are compiling ProFTPD from source, you can specify the directories in which to search for libraries, and their order, using the `--with-libraries` configure option.

**Comment by Shailendranjain** [comment] 2022-02-23 16:37
The issue got resolved once mysql-lib package was deployed. This package had provided mysqlclient, crypto shared libraries under /usr/lib64.

**Comment by Shailendranjain** [comment] 2022-02-23 16:38
Thanks for your prompt response

**Comment by Castaglia** [comment] 2022-02-23 16:41
I'm glad you were able to find a solution; hopefully this particular ticket's findings will help others who might encounter this subtle issue in the future.

**Comment by Castaglia** [comment] 2022-02-24 18:09
@Shailendranjain Should I consider this issue as addressed, and close this ticket then?

**Comment by Shailendranjain** [comment] 2022-11-14 19:04
> @Shailendranjain Should I consider this issue as addressed, and close this ticket then? 

Sorry for the delay. Please close this ticket

**Closed** 2022-11-15 00:42 UTC
Labels: configuration
