### ISSUE TITLE
Proftpd 1.3.6a does not have mysql 8 support

### ISSUE THREAD

**Issue by snjain** [proftpd/proftpd#841] opened 2019-10-16 22:21 UTC
### What I did

Tested proftpd version 1.3.6a and looks like it is not compatible with MySQL 8 as I am getting an error related to my_bool data type.

### What I Expected/Wanted

Please describe what behavior you wanted to achieve, what you expected to see.

Expectation was that proftpd stable release 1.3.6a is compatible with MySQL 8

### ProFTPD Version and Configuration

    $ proftpd -V

        1.3.6a

In addition, we need to see *all* of the ProFTPD configuration files you are
using (*minus* any sensitive information like passwords, of course).  Armed
with the version and configuration data, then, we can set up ProFTPD locally
using the same configuration, and see what happens.

**Comment by Castaglia** [comment] 2019-10-17 18:17
This looks to be a duplicate of Issue #824 .  Is this a request, then, to backport that fix to the 1.3.6 branch?

**Comment by snjain** [comment] 2019-10-17 22:36
Yes, requesting to back port the fix to 1.3.6. Also please advise once this is available in 1.3.6 branch

**Comment by Castaglia** [comment] 2019-10-18 15:30
I have backported the change to the 1.3.6 branch; see https://github.com/proftpd/proftpd/commit/5736774e9efa736dfaed991d9223710a1261e14a.

**Closed by Castaglia** 2019-10-18 15:30 UTC

**Comment by snjain** [comment] 2019-10-18 16:44
Thank you very much !

That was very fast :) 

Can you please advise when will the next official release happen for 1.3.6 branch (1.3.6b??)
