### ISSUE TITLE
Logging for specific users does not work

### ISSUE THREAD

**Issue by networkoper** [proftpd/proftpd#1705] opened 2023-08-27 18:18 UTC
**ProFTPD Version 1.3.8 / Debian 12**

I configure logging for a specific user, but logging does not happen. I don't get any errors, here is the configuration of my settings:

```
<IfModule mod_dso.c>
    RequireValidShell off
    AuthUserFile /etc/proftpd/ftpd.passwd
    AuthGroupFile /etc/proftpd/ftpd.group
    AuthOrder mod_auth_file.c
    LoadModule mod_ifsession.c
</IfModule>

Logformat userlog "%{iso8601} %a %u %s \%r %d"

<IfModule mod_ifsession.c>
  <IfUser userBOB>
    ExtendedLog /var/log/proftpd/userBOB.log READ,WRITE,INFO,EXIT userlog
  </IfUser>
</IfModule>
```

**Comment by Castaglia** [comment] 2023-09-02 19:54
ProFTPD is not well suited for generating per-user log files.

The issue is that any configured log file is opened very early in the session lifecycle, before privileges are dropped and before any `DefaultRoot`/chroot occurs.  Privileges are dropped, and chroots happen, as part of the authentication process -- which is precisely when we learn the identity of the remote user.

Log files cannot be easily opened _after_ authentication, due to lack of permissions in many cases, and due to inaccessibility of the configured log path once a chroot occurs.

Obtaining per-user log files from ProFTPD logging is best done by post-processing the log files generated by ProFTPD, and not by having ProFTPD itself support per-user logging.

**Comment by Castaglia** [comment] 2024-03-23 20:40
If there's nothing more to add to this ticket, I'd like to close it.  Thanks!

**Closed** 2024-09-07 16:47 UTC
Labels: waiting for feedback
