### ISSUE TITLE
Confusing asymmetrical "session closed" log message without preceding "session opened" log message

### ISSUE THREAD

**Issue by 3dw1n** [proftpd/proftpd#1539] opened 2022-10-17 10:10 UTC
### What I Did

I have a proftpd server setup with ftp, sftp, explicit ftps and implicit ftps running on AWS behind a Network Loadbalancer where I try to get rid of any logging which is related to Loadbalancer monitoring.
With the configs shown below I managed to get rid of all NLB monitoring traffic except the implicit ftps 'FTP session closed." messages in system.log.

With ftp/ftps/sftp enabled and all logging enabled, we see connect on port 21 and disconnect, we see connect on port 22 and SSH2 session closed.
We don't see port 990 connect but we do see an extra FTP session closed.:
```
2022-10-17 09:26:08,014 ftp-server.com proftpd[1373047] ftp-server.com: ProFTPD 1.3.8rc4 (devel) (built Mon Oct 17 2022 08:34:45 UTC) standalone mode STARTUP
2022-10-17 09:26:13,002 ftp-server.com proftpd[1373149] ftp-server.com (network.loadbalancer.aws): connected - local  : ftp-server.com:21
2022-10-17 09:26:13,002 ftp-server.com proftpd[1373149] ftp-server.com (network.loadbalancer.aws): connected - remote : network.loadbalancer.aws:15859
2022-10-17 09:26:13,002 ftp-server.com proftpd[1373149] ftp-server.com (network.loadbalancer.aws): FTP session opened.
2022-10-17 09:26:13,003 ftp-server.com proftpd[1373149] ftp-server.com (network.loadbalancer.aws): FTP session closed.
2022-10-17 09:26:13,786 ftp-server.com proftpd[1373172] ftp-server.com (network.loadbalancer.aws): FTP session closed.
2022-10-17 09:26:17,181 ftp-server.com proftpd[1373233] ftp-server.com (network.loadbalancer.aws): connected - local  : ftp-server.com:22
2022-10-17 09:26:17,181 ftp-server.com proftpd[1373233] ftp-server.com (network.loadbalancer.aws): connected - remote : network.loadbalancer.aws:41353
2022-10-17 09:26:17,181 ftp-server.com proftpd[1373233] ftp-server.com (network.loadbalancer.aws): SSH2 session opened.
2022-10-17 09:26:17,181 ftp-server.com proftpd[1373233] ftp-server.com (network.loadbalancer.aws): mod_sftp/1.1.1: scrubbing 1 passphrase from memory
2022-10-17 09:26:17,181 ftp-server.com proftpd[1373233] ftp-server.com (network.loadbalancer.aws): SSH2 session closed.
```
Let's try and isolate the implicit ftps logs, only ftp/ftps enabled (commented out Include /ftp-server/proftpd/etc/proftpd.sftp.conf in proftpd.conf) and ftp port changed to 999 so only loadbalancer monitoring port 999 traffic comes through:
```
2022-10-17 09:31:45,610 ftp-server.com proftpd[1379868] ftp-server.com: ProFTPD 1.3.8rc4 (devel) (built Mon Oct 17 2022 08:34:45 UTC) standalone mode STARTUP
2022-10-17 09:31:53,786 ftp-server.com proftpd[1380031] ftp-server.com (network.loadbalancer.aws): FTP session closed.
2022-10-17 09:32:03,786 ftp-server.com proftpd[1380222] ftp-server.com (network.loadbalancer.aws): FTP session closed.
```
So it is the implicit ftps virtual host which is the source of the FTP session closed messages which I would like to disable.

Now with ftp/ftps/sftp enabled and logging disabled with Class loadbalancer (see proftpd.conf) still showing implicit ftps disconnects
```
2022-10-17 09:27:40,444 ftp-server.com proftpd[1374937] ftp-server.com: ProFTPD 1.3.8rc4 (devel) (built Mon Oct 17 2022 08:34:45 UTC) standalone mode STARTUP
2022-10-17 09:27:43,786 ftp-server.com proftpd[1375025] ftp-server.com (network.loadbalancer.aws): FTP session closed.
2022-10-17 09:27:53,809 ftp-server.com proftpd[1375215] ftp-server.com (network.loadbalancer.aws): FTP session closed.
```
### What I Expected/Wanted

I expected not to see the FTP session closed messages anymore with the Class/IfClass construction as in the configuration files below. It does work for ftp and sftp but not for the ftps virtual host.

### ProFTPD Version and Configuration
```
-------------------------------------------------------------------------------
proftpd.conf:
-------------------------------------------------------------------------------
ServerType    standalone
DefaultServer on
Port          999
UseIPv6       off

<Class loadbalancer>
    # the whole VPC private net which includes the NLB's private ip
    From 172.20.0.0/16
</Class>

<Global>
    RootLogin           off
    DefaultRoot         ~
    RequireValidShell   off
    User                nobody
    Group               nobody
    AllowEmptyPasswords off
    DebugLevel          10
    SyslogLevel         debug

    #AuthOrder mod_auth_file.c
    AuthGroupFile /ftp-server/proftpd/etc/proftpd.group
    AuthUserFile  /ftp-server/proftpd/etc/proftpd.passwd

    <IfModule mod_log.c>
        SystemLog   /ftp-server/proftpd/var/log/system.log
        TransferLog /ftp-server/proftpd/var/log/xferlog
        ExtendedLog /ftp-server/proftpd/var/log/proftpd.log ALL,EXIT

        <IfClass loadbalancer>
          # Disable all logging for loadbalancer traffic
          SystemLog   none
          ExtendedLog /ftp-server/proftpd/var/log/proftpd.log none
          TransferLog none
        </IfClass>
    </IfModule>

</Global>

<IfModule mod_tls.c>
    Include /ftp-server/proftpd/etc/proftpd.ftps.conf
</IfModule>

<IfModule mod_sftp.c>
    Include /ftp-server/proftpd/etc/proftpd.sftp.conf
</IfModule>
-------------------------------------------------------------------------------
```
```
-------------------------------------------------------------------------------
proftpd.ftps.conf
-------------------------------------------------------------------------------
<IfModule mod_tls.c>

    # first Explicit SSL
    TLSEngine   on
    TLSRequired off

    TLSRSACertificateFile    /root/zerossl/ftp-server.com.crt
    TLSRSACertificateKeyFile /root/zerossl/ftp-server.com.key
    TLSCertificateChainFile  /root/zerossl/lets-encrypt-x3-cross-signed.crt

    # Implicit SSL in seperate virtual host!
    <VirtualHost %{env:HOSTNAME} >
        TLSEngine   on
        TLSRequired on
        Port        990
        TLSOptions UseImplicitSSL

        TLSRSACertificateFile    /root/zerossl/ftp-server.com.crt
        TLSRSACertificateKeyFile /root/zerossl/ftp-server.com.key
        TLSCertificateChainFile  /root/zerossl/lets-encrypt-x3-cross-signed.crt
    </VirtualHost>
</IfModule>
-------------------------------------------------------------------------------
```
```
-------------------------------------------------------------------------------
proftpd.sftp.conf
-------------------------------------------------------------------------------
<IfModule mod_sftp.c>
    <VirtualHost %{env:HOSTNAME} >
        SFTPEngine      on
        SFTPAuthMethods password
        Port            22
        SFTPHostKey     /maccsbox/proftpd/etc/ssh_host_rsa4096_key
    </VirtualHost>
</IfModule>
-------------------------------------------------------------------------------
```
```
-------------------------------------------------------------------------------
proftpd -V
-------------------------------------------------------------------------------
Compile-time Settings:
  Version: 1.3.8rc4 (devel)
  Platform: LINUX [Linux 5.15.43-20.123.amzn2022.x86_64 x86_64]
  OS/Release:
    NAME="Amazon Linux"
    VERSION="2022"
    ID="amzn"
    ID_LIKE="fedora"
    VERSION_ID="2022"
    PLATFORM_ID="platform:al2022"
    PRETTY_NAME="Amazon Linux 2022"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2022"
  Built: Mon Oct 17 2022 08:34:45 UTC
  Built With:
    configure  '--prefix=/maccsboxplus/proftpd' '--with-modules=mod_aws:mod_sftp:mod_tls:mod_sql:mod_ban:mod_sql_mysql:mod_sftp_sql:mod_proxy_protocol:mod_ifsession' '--enable-nls' '--enable-ctrls' '--with-includes=/root/mariadb-10.3.31-linux-x86_64/include/mysql:/usr/include/curl:/usr/include/libxml2:/usr/include/openssl' '--with-libraries=/root/mariadb-10.3.31-linux-x86_64/lib'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing
  LDFLAGS: -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic -L/root/mariadb-10.3.31-linux-x86_64/lib
  LIBS:  -lssl -lcrypto -lsodium -lm -lmysqlclient -lz  -lssl  -lcurl -lxml2 -lcrypto -lcrypt  -pthread

  Files:
    Configuration File:
      /maccsboxplus/proftpd/etc/proftpd.conf
    Pid File:
      /maccsboxplus/proftpd/var/proftpd.pid
    Scoreboard File:
      /maccsboxplus/proftpd/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    + OpenSSL support (OpenSSL 3.0.3 3 May 2022)
    - PCRE support
    - PCRE2 support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
-------------------------------------------------------------------------------
```

**Comment by Castaglia** [comment] 2022-10-22 18:10
Am I correct in assuming that your NLB is configured to perform a TCP connect as its health check, to port 999 (and *not* ports 21, 22, 990)?  I'm wanting to reproduce this behavior locally, and want to make sure my local configuration (in terms of load balancer/health check behavior) is correct.

**Comment by Castaglia** [comment] 2022-10-22 18:13
Also, what I find interesting in your provided excerpts, _e.g._:
```
2022-10-17 09:27:43,786 ftp-server.com proftpd[1375025] ftp-server.com (network.loadbalancer.aws): FTP session closed.
2022-10-17 09:27:53,809 ftp-server.com proftpd[1375215] ftp-server.com (network.loadbalancer.aws): FTP session closed.
```
is that the PIDs in these two log messages is different -- indicating that they are different processes (and thus different TCP connections), not the same process.  Or are you saying that these are indeed different TCP connections (from the NLB), without the accompanying "session opened" log messages (as expected, because of your logging filtering)?

**Comment by 3dw1n** [comment] 2022-10-27 11:19
MY apologies for the late response... 

Yes the NLB (AWS Network Loadbalancer) has listeners for ports 21, 22 and 990.

Yes the PID in the two log messages is different because it's the monitoring process that tries to connect every 10 seconds, so these log messages are as you say indeed different TCP connections (from the NLB), without the accompanying "session opened" log messages (as expected, because of your logging filtering).

**Comment by Castaglia** [comment] 2022-10-29 15:24
@3dw1n Got it. Then, just to make sure I'm understanding correctly, your question is why these "FTP session closed" messages are being logged for these NLB health check TCP probes _at all_, when their accompanying "session opened" messages are *not* being logged.  Is that correct?

**Comment by Castaglia** [comment] 2022-10-29 16:35
OK, I think I see what's happening here; it's related to module load ordering, and the order in which different modules handle the new TCP connection (from the NLB).

The module load order is determined by the order of modules in the `--with-modules` configure option.  Modules' functions are invoked in the _reverse_ order of the `--with-modules` list; last module listed, first module called.  This is why `mod_ifsession` *must* be last -- so that its ability to alter the in-memory configuration, *before* the other modules look up that configuration, is invoked as one of the first things during handling of a new connection.

The "session opened" log message is logged _after_ all modules have successfully passed their "connection initialization" functions.  This means that if _any_ module fails its "connection initialization" check, that connection is rejected/closed, and the "session opened" message is *not logged*.  So far, so good.

The "implicit FTPS" functionality of `mod_tls` is implemented as one of these "connection initialization" checks, since the TLS handshake, for implicit FTPS, is by definition one of the very first parts of the TCP bytes on the wire.  The AWS NLB health check, being a simple TCP probe (and not a TLS check), fails this TLS handshake, thus causing the `mod_tls` "connection initialization" check to fail -- and thus the "session opened" log message does not appear.

Why do we see a "session closed" message, then, for these rejected connections?  That log message is automatically done whenever the TCP connection is closed.  And currently, this logging does not check that all of the "connection initialization" checks succeeded.  And perhaps it should?

As a workaround, you might change your configuration such that `SystemLog` is disabled _by default_, and is only _enabled_ for non-loadbalancer connections.  For example, your configuration might instead be:
```
-------------------------------------------------------------------------------
proftpd.conf:
-------------------------------------------------------------------------------
ServerType    standalone
DefaultServer on
Port          999
UseIPv6       off

<Class loadbalancer>
    # the whole VPC private net which includes the NLB's private ip
    From 172.20.0.0/16
</Class>

<Global>
    RootLogin           off
    DefaultRoot         ~
    RequireValidShell   off
    User                nobody
    Group               nobody
    AllowEmptyPasswords off
    DebugLevel          10
    SyslogLevel         debug

    #AuthOrder mod_auth_file.c
    AuthGroupFile /ftp-server/proftpd/etc/proftpd.group
    AuthUserFile  /ftp-server/proftpd/etc/proftpd.passwd

    <IfModule mod_log.c>
        SystemLog   /ftp-server/proftpd/var/log/system.log
        TransferLog /ftp-server/proftpd/var/log/xferlog
        ExtendedLog /ftp-server/proftpd/var/log/proftpd.log ALL,EXIT

        <IfClass !loadbalancer>
          # Enable all logging for non-loadbalancer traffic
          SystemLog   /ftp-server/proftpd/var/log/system.log
          TransferLog /ftp-server/proftpd/var/log/xferlog
          ExtendedLog /ftp-server/proftpd/var/log/proftpd.log ALL,EXIT
        </IfClass>
    </IfModule>
</Global>

<IfModule mod_tls.c>
    Include /ftp-server/proftpd/etc/proftpd.ftps.conf
</IfModule>

<IfModule mod_sftp.c>
    Include /ftp-server/proftpd/etc/proftpd.sftp.conf
</IfModule>
-------------------------------------------------------------------------------
```

**Comment by 3dw1n** [comment] 2022-10-31 07:54
Thanks for figuring this out and explaining it thoroughly, I will try your workaround suggestion, thanks again!

**Comment by 3dw1n** [comment] 2022-11-01 12:05
Ok, I played around with it some more and found the correct way to configure this I think.

First the **not-working** config:

```
    # not-working, FTP Session closed for ftps still logged
    <IfModule mod_log.c>

        # enable logging
        SystemLog   /proftpd/var/log/system.log
        TransferLog /proftpd/var/log/xferlog
        ExtendedLog /proftpd/var/log/proftpd.log ALL,EXIT

        # disable logging for loadbalancer traffic
        <IfClass loadbalancer>
          SystemLog   none
          ExtendedLog /proftpd/var/log/proftpd.log none
          TransferLog none
        </IfClass>

    </IfModule>
```

The above config in `<Global>` does give the FTP Session closed messages for NLB tcps healthchecks,

With the config below the **FTP Session closed messages are no longer logged**. So Apparently there is
a difference between just configuring those logs and disabling them with IfClass and using IfClass and IfClass !.

```
    # working!!! FTP Session closed for ftps still logged
    <IfModule mod_log.c>

        # enable logging for non-loadbalancer traffic
        <IfClass !loadbalancer>
            SystemLog   /proftpd/var/log/system.log
            TransferLog /proftpd/var/log/xferlog
            ExtendedLog /proftpd/var/log/proftpd.log ALL,EXIT
        </IfClass>

        # disable logging for loadbalancer traffic
        <IfClass loadbalancer>
            SystemLog   none
            ExtendedLog /proftpd/var/log/proftpd.log none
            TransferLog none
        </IfClass>

    </IfModule>
```
	
Just for the sake of completeness I also tried the config below which also gives the FTP Session closed
messages.

```
    # not-working, FTP Session closed for ftps still logged
    <IfModule mod_log.c>
        
        # enable logging
	SystemLog   /proftpd/var/log/system.log
        TransferLog /proftpd/var/log/xferlog
        ExtendedLog /proftpd/var/log/proftpd.log ALL,EXIT

        # enable logging for non-loadbalancer traffic        
	<IfClass !loadbalancer>
            SystemLog   /proftpd/var/log/system.log
            TransferLog /proftpd/var/log/xferlog
            ExtendedLog /proftpd/var/log/proftpd.log ALL,EXIT
        </IfClass>

        # disable logging for loadbalancer traffic
        <IfClass loadbalancer>
            SystemLog   none
            ExtendedLog /proftpd/var/log/proftpd.log none
            TransferLog none
        </IfClass>

    </IfModule>

```

**Comment by Castaglia** [comment] 2022-11-10 01:25
Now fixed in master.  Thanks!

**Closed by Castaglia** 2022-11-10 01:25 UTC
Labels: bug, question
