### ISSUE TITLE
does not support > 32 bit signed integers

### ISSUE THREAD

**Issue by barrychapman** [proftpd/proftpd#74] opened 2014-11-19 06:08 UTC
It is breaking our user ids since we have some user ids that are long sets of digits.

Is there a workaround?

**Comment by Castaglia** [comment] 2015-03-15 21:40
When you say "looking at the log file", could you be more specific?  Which log file?  Could you include the full message?  (Sorry for the delay in getting back to this issue; I'm in the midst of setting up a repro case for this now, if I can.)

**Comment by Castaglia** [comment] 2015-03-15 21:55
I found the root cause of the bug, and filed a bug report in our Bugzilla instance; see:

  http://bugs.proftpd.org/show_bug.cgi?id=4164

I should have a fix for this shortly.

**Comment by Castaglia** [comment] 2015-03-16 04:34
https://github.com/proftpd/proftpd/pull/95 should help with this.  Note that some of the logging, throughout the codebase, still needs improvement.

**Comment by Castaglia** [comment] 2015-03-20 15:57
This should now be fixed in master; the above pull request was merged.  Please try out the master branch; if you still have issues with larger IDs, please reopen this issue, and provide the `proftpd -V' output (I've added lines to the output, to show the max UID/GID value supported by the platform's uid_t/gid_t data types).  Thanks!

**Closed by Castaglia** 2015-03-20 15:57 UTC
