### ISSUE TITLE
Proftpd acting up, huge load and generally terrible performance

### ISSUE THREAD

**Issue by mflage** [proftpd/proftpd#1031] opened 2020-06-14 07:53 UTC
### What I Did

We've had a server running for several weeks in the cloud. This was used for retrieving files and then index this into a http-accessible archive. Uploads were generally happening every 20 minutes, with 5 parallel upload sessions. Now and then this can be up to 10. Over the last couple of days we've experienced sluggish performance of the server and now the last day this has completely halted the performance of the server.

I tried stracing one of the proftpd processes and saw this:

```
strace: Process 20222 attached
select(20, [19], NULL, NULL, {tv_sec=0, tv_usec=264118}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
select(20, [19], NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
```

Doesn't look good at all. And additionally I see the following in /var/log/proftpd/proftpd.log:

```
2020-06-14 07:43:43,936 b2-120-de1 proftpd[20067] 127.0.1.1 (1.1.1.1[1.1.1.1]): Data transfer stall timeout: 600 seconds
2020-06-14 07:43:43,936 b2-120-de1 proftpd[20067] 127.0.1.1 (1.1.1.1[1.1.1.1]): notice: user sentinel-upload: aborting transfer: Data connection closed
2020-06-14 07:43:43,937 b2-120-de1 proftpd[20067] 127.0.1.1 (1.1.1.1[1.1.1.1]): FTP session closed.
2020-06-14 07:44:32,658 b2-120-de1 proftpd[20073] 127.0.1.1 (1.1.1.1[1.1.1.1]): Data transfer stall timeout: 600 seconds
2020-06-14 07:44:32,659 b2-120-de1 proftpd[20073] 127.0.1.1 (1.1.1.1[1.1.1.1]): notice: user sentinel-upload: aborting transfer: Data connection closed
2020-06-14 07:44:32,659 b2-120-de1 proftpd[20073] 127.0.1.1 (1.1.1.1[1.1.1.1]): FTP session closed.
2020-06-14 07:44:37,709 b2-120-de1 proftpd[20075] 127.0.1.1 (1.1.1.1[1.1.1.1]): Data transfer stall timeout: 600 seconds
2020-06-14 07:44:37,710 b2-120-de1 proftpd[20075] 127.0.1.1 (1.1.1.1[1.1.1.1]): notice: user sentinel-upload: aborting transfer: Data connection closed
2020-06-14 07:44:37,710 b2-120-de1 proftpd[20075] 127.0.1.1 (1.1.1.1[1.1.1.1]): FTP session closed.
2020-06-14 07:45:00,850 b2-120-de1 proftpd[20079] 127.0.1.1 (1.1.1.1[1.1.1.1]): Data transfer stall timeout: 600 seconds
2020-06-14 07:45:00,850 b2-120-de1 proftpd[20079] 127.0.1.1 (1.1.1.1[1.1.1.1]): notice: user sentinel-upload: aborting transfer: Data connection closed
2020-06-14 07:45:00,851 b2-120-de1 proftpd[20079] 127.0.1.1 (1.1.1.1[1.1.1.1]): FTP session closed.
```

I also see the following kernel dump:

```
[1762538.589385] warn_alloc: 4201 callbacks suppressed
[1762538.589389] swapper/9: page allocation failure: order:0, mode:0x1080020(GFP_ATOMIC), nodemask=(null)
[1762538.589391] swapper/9 cpuset=/ mems_allowed=0
[1762538.589407] CPU: 9 PID: 0 Comm: swapper/9 Not tainted 4.15.0-99-generic #100-Ubuntu
[1762538.589408] Hardware name: OpenStack Foundation OpenStack Nova, BIOS 2:1.10.2-58953eb7 04/01/2014
[1762538.589409] Call Trace:
[1762538.589412]  <IRQ>
[1762538.589924]  dump_stack+0x6d/0x8e
[1762538.590351]  warn_alloc+0xff/0x1a0
[1762538.590355]  __alloc_pages_slowpath+0xdc5/0xe00
[1762538.590715]  ? tcp_rcv_established+0x2f1/0x590
[1762538.590717]  ? tcp_v4_do_rcv+0x90/0x1d0
[1762538.590719]  __alloc_pages_nodemask+0x29a/0x2c0
[1762538.590721]  page_frag_alloc+0x11f/0x150
[1762538.590724]  __napi_alloc_skb+0x8f/0xf0
[1762538.590851]  page_to_skb+0x63/0x310 [virtio_net]
[1762538.590854]  receive_buf+0x794/0x14c0 [virtio_net]
[1762538.590857]  ? __netif_receive_skb_core+0x432/0xb80
[1762538.590865]  ? vring_unmap_one+0x1b/0x80
[1762538.590867]  ? detach_buf+0x71/0x120
[1762538.590869]  virtnet_poll+0x152/0x2bd [virtio_net]
[1762538.590871]  net_rx_action+0x140/0x3a0
[1762538.590875]  __do_softirq+0xe4/0x2d4
[1762538.590879]  irq_exit+0xc5/0xd0
[1762538.590880]  do_IRQ+0x86/0xe0
[1762538.590885]  common_interrupt+0x8c/0x8c
[1762538.590885]  </IRQ>
[1762538.590888] RIP: 0010:native_safe_halt+0x12/0x20
[1762538.590889] RSP: 0018:ffffb908062dbe80 EFLAGS: 00000246 ORIG_RAX: ffffffffffffffd9
[1762538.590891] RAX: ffffffff87fc1500 RBX: 0000000000000009 RCX: 0000000000000000
[1762538.590892] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[1762538.590892] RBP: ffffb908062dbe80 R08: 0000000000000002 R09: 0000000000000001
[1762538.590893] R10: 0000000000000000 R11: 00000000000007fe R12: 0000000000000009
[1762538.590894] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[1762538.590896]  ? __sched_text_end+0x1/0x1
[1762538.590898]  default_idle+0x20/0x100
[1762538.590903]  arch_cpu_idle+0x15/0x20
[1762538.590904]  default_idle_call+0x23/0x30
[1762538.590909]  do_idle+0x172/0x1f0
[1762538.590911]  cpu_startup_entry+0x73/0x80
[1762538.590915]  start_secondary+0x1ab/0x200
[1762538.591016]  secondary_startup_64+0xa5/0xb0
```

The server runs without swap space, but it has 130GB worth of RAM. I also see lots of load on the server (around 7-8) and all proftpd forks consuming 100 % CPU.

### What I Expected/Wanted

I expected proftpd would be able to handle up to 10 parallel sessions without any issues.

### ProFTPD Version and Configuration

```
Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 4.15.0-99-generic x86_64]
  Built: Mon Feb 5 2018 23:27:47 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--with-modules=mod_readme' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_tls_memcache:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security -Wall
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS:  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lpam -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncurses support
    + NLS support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment] 2020-06-28 23:32
I've seen ProFTPD easily handle more than 10 concurrent sessions; I suspect this issue lies with some other aspect/behavior of the clients (and configuration used).

Are you able to easily reproduce this behavior?  That would greatly help in diagnosing this, so that we can reproduce the behavior locally, and track down causes.

**Comment by Castaglia** [comment] 2021-11-27 23:17
If there's nothing more to add to this ticket, I'd like to close it.

**Comment by Castaglia** [comment] 2022-02-19 18:40
Closing this ticket due to lack of activity.  Please open new tickets for any issues you see going forward.  Thanks!

**Closed by Castaglia** 2022-02-19 18:40 UTC
Labels: waiting for feedback
