### ISSUE TITLE
Can't connect to postgre db to make a query

### ISSUE THREAD

**Issue by ieguinoa** [proftpd/proftpd#783] opened 2019-02-12 14:46 UTC
Hi all,
I'm trying to add a SQL query to a ftp to retrieve login information from a postre sql server.
I know the server, db and the connection is all working ok because I can make queries directly from the ftp server (e.g through a python script)

I think the query is correct but in any case it never gets executed because somehow it fails to connect to the db server. 

**The SQLLogFile content is:**
```
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: defaulting to 'postgres' backend
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: backend module 'mod_sql_postgres/4.0.4'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: backend api    'mod_sql_api_v1'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: >>> sql_sess_init
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: entering   postgres cmd_defineconnection
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:  name: 'default'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:  user: 'galaxy_prod'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:  host: '10.10.6.13'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:    db: 'galaxy_prod_db'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:  port: '5432'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]:   ttl: '0'
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: exiting    postgres cmd_defineconnection
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: connection 'default' successfully established
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: mod_sql engine     : on
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: negative_cache     : off
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: authenticate       : users
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: usertable          : users
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: userid field       : userid
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: password field     : passwd
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: UID field          : uid
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: GID field          : gid
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: homedir field      : homedir
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: shell field        : shell
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: SQLMinUserUID      : 999
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: SQLMinUserGID      : 999
2019-02-12 15:19:46,944 mod_sql/4.3[178061]: <<< sql_sess_init
2019-02-12 15:19:49,045 mod_sql/4.3[178061]: >>> sql_escapestr
2019-02-12 15:19:49,045 mod_sql/4.3[178061]: entering   postgres cmd_escapestring
2019-02-12 15:19:49,045 mod_sql/4.3[178061]: entering   postgres cmd_open
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: exiting    postgres cmd_open
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: exiting    postgres cmd_escapestring
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: unrecoverable backend error
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: error: 'mod_sql_postgres/4.0.4'
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: message: 'could not connect to server: Permission denied
        Is the server running on host "10.10.6.13" and accepting
        TCP/IP connections on port 5432?
'
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: entering   postgres cmd_exit
2019-02-12 15:19:49,046 mod_sql/4.3[178061]: exiting    postgres cmd_exit
```

 

**Output from proftpd -V**
```
Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 3.10.0-862.11.6.el7.x86_64 x86_64]
  Built: Wed Jan 31 2018 16:32:29 UTC
  Built With:
    configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-shadow' '--enable-tests' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic'

  CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64/mysql -L/usr/lib64/mysql -L/usr/lib64
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lssl -lcrypto  -lpam -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (FIPS enabled)
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

Any idea will be appreciated.
thanks!
Ignacio

**Comment by Castaglia** [comment] 2019-04-20 18:12
Would it be possible to see the `proftpd.conf` that you are using, particular the `mod_sql` configuration section?  Without any sensitive usernames/passwords, that is.  I am hoping to see just how you have configured `mod_sql` to connect to your Postgres database, so that I can attempt to reproduce the issue locally.  Thanks!

**Comment by Castaglia** [comment] 2019-12-21 22:58
If there's nothing more to provide/add to this ticket, I'm afraid I will have to close it as being stale/undesired.

**Comment by kingrius** [comment] 2020-04-13 16:58
Hi,
since january i have been trying to solve the same problem without success and i really need help.
Best regards

**Comment by Castaglia** [comment] 2021-06-26 22:24
@kingrius @ieguinoa Unless config files, and debug logging, is provided, then we cannot make progress on address this.  I will close this ticket soon, if no further information is provided.

**Comment by Castaglia** [comment] 2021-08-08 22:26
No further details/information provided; closing this ticket.

**Closed by Castaglia** 2021-08-08 22:26 UTC
Labels: configuration
