### ISSUE TITLE
Support bcrypt passwords in mod_sql_passwd

### ISSUE THREAD

**Issue by lon9man** [proftpd/proftpd#692] opened 2018-04-26 16:00 UTC
Fast question:
Does ProFTPd plans to implement Bcrypt-method for Mod_SQL_Passwd?

**Comment by betterphp** [comment] 2019-01-01 21:36
I'd also be interested in this, we're hoping to be able to authenticate sftp users against our existing database.

**Comment by Castaglia** [comment] 2019-10-20 00:26
Are you thinking that the value stored in the database would start with the `$2b$...` prefix, as if the value were coming from an `/etc/passwd`/`/etc/shadow` file?

**Comment by lon9man** [comment] 2019-10-20 07:05
@Castaglia i am not sure in your question, but in general:
1. We have database table Users with accounts (bcrypt hashed passwords)
2. We have separate table FtpUsers with proftpd-accounts (md5 hashed passwords)

But we thought to have 1 table for both purposes. Saying user changes own password and it will be changed for FTP also. In opposite now we should to make additional actions to sync and rehash with different methods both passwords.

Thanks

**Comment by Castaglia** [comment] 2019-10-20 16:29
Could you provide an example bcrypt field, or, say, generate a test one using a password of "password"?  There are multiple ways of encoding password hashes; I am trying to determine just which format/encoding is used in your systems, so that I see what it would take to implement in ProFTPD.

**Comment by lon9man** [comment] 2019-10-21 05:41
@Castaglia,
i am using Zend Framework 2 and package zend-crypt (https://packagist.org/packages/zendframework/zend-crypt).
code sample:
```
$password = 'password';
$cost = 14;

$bcrypt = new Bcrypt();
$bcrypt->setCost($cost);
$hash = $bcrypt->create($password);
```

generated **$hash** for _'password'_ equals to **$2y$14$r5BQoR3rAFQGnOEh73QrOOIsQJPjIYVF76IitsqqA7ix51SE/llCG**

thanks

P.S. feel free to ask anything else if needed

**Comment by Castaglia** [comment] 2019-10-23 01:23
Thanks.  Interesting that that `$2y$` prefix uses `y`; most bcrypt implementations, in C, use `$2$`, or maybe `$2a$` or `$2b$`.  Looks like `$2y$`' is [specific to PHP](https://www.php.net/manual/en/function.password-hash.php):
> PASSWORD_BCRYPT - Use the CRYPT_BLOWFISH algorithm to create the hash. This will produce a standard crypt() compatible hash using the "$2y$" identifier.

I'll make sure that the ProFTPD implementation handles this variant.

**Comment by Castaglia** [comment] 2019-10-23 02:51
This is now implemented in `mod_sql_passwd`, and merged to master.

**Closed by Castaglia** 2019-10-23 02:51 UTC
Labels: enhancement

**Comment by lon9man** [comment] 2019-10-24 08:35
@Castaglia, i have tried to test **bcrypt**. strange, but it doesn't work for me.

**What i did**
1. rebuilt proftpd from latest sources (got version 1.3.7rc3). 
2. put hash **$2y$14$r5BQoR3rAFQGnOEh73QrOOIsQJPjIYVF76IitsqqA7ix51SE/llCG** for password **"password"** into database table
3. changed config to
```
SQLAuthTypes             bcrypt
SQLPasswordEngine        on
SQLPasswordEncoding      base64
```
4. restarted proftpd-service

**What i get**
try to connect using FileZilla and password "password" and unable to connect
```
Status:	Waiting to retry...
Status:	Resolving address of localhost
Status:	Connecting to [::1]:21...
Status:	Connection established, waiting for welcome message...
Response:	220 ProFTPD Server (Debian) [::1]
Command:	AUTH TLS
Response:	500 AUTH not understood
Command:	AUTH SSL
Response:	500 AUTH not understood
Status:	Insecure server, it does not support FTP over TLS.
Command:	USER lon9man
Response:	331 Password required for lon9man
Command:	PASS *********
Error:	Connection closed by server
Error:	Could not connect to server
```

i have tested different configs, saw your test logic in commit (https://github.com/proftpd/proftpd/commit/e7120fab664ea432189d6fcf74341b7db0a8511f), checked logs, but didn't find some useful information.

**Questions**
1. how i can debug the reason of this behaviour?
maybe i missed something important?

**Comment by Castaglia** [comment] 2019-10-25 02:11
To debug this, you should configure an [`SQLLogFile`](http://www.proftpd.org/docs/contrib/mod_sql.html#SQLLogFile), _and_ a [`TraceLog`](http://www.proftpd.org/docs/howto/Tracing.html) file, _e.g._:
```
<IfModule mod_sql.c>
  ...
  SQLLogFile /path/to/ftpd/sql.log
  TraceLog /path/to/ftpd/sql.log
  Trace sql:20 sql.passwd:20
  ...
</IfModule>
```
I used your generated password in my regression tests, and was able to login successfully.  Hopefully, when you configure the logging above, you might see more?

**Comment by lon9man** [comment] 2019-10-25 10:33
@Castaglia, very strange, but trace-log for **sql.passwd**-channel is empty. other channels don't have useful information.

Trace's config 
```
SQLLogFile /path/to/ftpd/sql.log
TraceLog /path/to/ftpd/trace.log
Trace auth:20 sql:20 sql.passwd:20
```

trace.log:
```
...
2019-10-25 13:22:41,885 [3670] <auth:6>: dispatching auth request "getgroups" to module mod_sql
2019-10-25 13:22:41,885 [3670] <auth:6>: dispatching auth request "getgroups" to module mod_auth_file
2019-10-25 13:22:41,885 [3670] <auth:6>: dispatching auth request "getgroups" to module mod_auth_unix
2019-10-25 13:22:41,885 [3670] <auth:4>: using initgroups(3) to look up group membership
2019-10-25 13:22:45,775 [3695] <sql:9>: loaded 'mysql' SQL backend
2019-10-25 13:22:45,775 [3695] <sql:19>: dispatching SQL command 'sql_identify'
2019-10-25 13:22:45,775 [3695] <sql:19>: dispatching SQL command 'sql_defineconnection'
2019-10-25 13:22:45,776 [3695] <auth:6>: dispatching auth request "endpwent" to module mod_sql
2019-10-25 13:22:45,776 [3695] <auth:6>: dispatching auth request "endgrent" to module mod_sql
2019-10-25 13:22:45,776 [3695] <auth:1>: error finding start symbol for 'requires_pass': No such file or directory
2019-10-25 13:22:45,776 [3695] <auth:6>: dispatching auth request "getpwnam" to module mod_sql
2019-10-25 13:22:45,776 [3695] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:45,780 [3695] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:45,780 [3695] <auth:5>: stashed module 'mod_sql.c' for user 'lon9man' in the authcache
2019-10-25 13:22:45,780 [3695] <auth:5>: stashed name 'lon9man' for UID 1000 in the uidcache
2019-10-25 13:22:45,780 [3695] <auth:5>: stashed UID 1000 for user 'lon9man' in the usercache
2019-10-25 13:22:45,780 [3695] <auth:6>: dispatching auth request "getgrgid" to module mod_sql
2019-10-25 13:22:45,780 [3695] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:45,781 [3695] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "getgroups" to module mod_sql
2019-10-25 13:22:45,781 [3695] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:45,781 [3695] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "endpwent" to module mod_sql
2019-10-25 13:22:45,781 [3695] <auth:5>: emptying authcache (1 item)
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "endgrent" to module mod_sql
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "getpwnam" to module mod_sql
2019-10-25 13:22:45,781 [3695] <auth:5>: stashed module 'mod_sql.c' for user 'lon9man' in the authcache
2019-10-25 13:22:45,781 [3695] <auth:9>: no value found in gidcache for GID 1000: No such file or directory
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "gid2name" to module mod_sql
2019-10-25 13:22:45,781 [3695] <auth:5>: stashed name 'longman' for GID 1000 in the gidcache
2019-10-25 13:22:45,781 [3695] <auth:6>: dispatching auth request "getgroups" to module mod_sql
2019-10-25 13:22:45,781 [3695] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:45,782 [3695] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:45,782 [3695] <auth:4>: using module 'mod_sql.c' from authcache to authenticate user 'lon9man'
2019-10-25 13:22:45,782 [3695] <auth:6>: dispatching auth request "auth" to module mod_sql
2019-10-25 13:22:45,782 [3695] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:45,782 [3695] <auth:4>: using module 'mod_sql.c' from authcache to authenticate user 'lon9man'
2019-10-25 13:22:45,782 [3695] <auth:6>: dispatching auth request "check" to module mod_sql
2019-10-25 13:22:50,784 [3697] <sql:9>: loaded 'mysql' SQL backend
2019-10-25 13:22:50,784 [3697] <sql:19>: dispatching SQL command 'sql_identify'
2019-10-25 13:22:50,784 [3697] <sql:19>: dispatching SQL command 'sql_defineconnection'
2019-10-25 13:22:50,785 [3697] <auth:6>: dispatching auth request "endpwent" to module mod_sql
2019-10-25 13:22:50,785 [3697] <auth:6>: dispatching auth request "endgrent" to module mod_sql
2019-10-25 13:22:50,785 [3697] <auth:1>: error finding start symbol for 'requires_pass': No such file or directory
2019-10-25 13:22:50,785 [3697] <auth:6>: dispatching auth request "getpwnam" to module mod_sql
2019-10-25 13:22:50,785 [3697] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:50,787 [3697] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:50,787 [3697] <auth:5>: stashed module 'mod_sql.c' for user 'lon9man' in the authcache
2019-10-25 13:22:50,787 [3697] <auth:5>: stashed name 'lon9man' for UID 1000 in the uidcache
2019-10-25 13:22:50,787 [3697] <auth:5>: stashed UID 1000 for user 'lon9man' in the usercache
2019-10-25 13:22:50,787 [3697] <auth:6>: dispatching auth request "getgrgid" to module mod_sql
2019-10-25 13:22:50,787 [3697] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:50,787 [3697] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "getgroups" to module mod_sql
2019-10-25 13:22:50,788 [3697] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:50,788 [3697] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "endpwent" to module mod_sql
2019-10-25 13:22:50,788 [3697] <auth:5>: emptying authcache (1 item)
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "endgrent" to module mod_sql
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "getpwnam" to module mod_sql
2019-10-25 13:22:50,788 [3697] <auth:5>: stashed module 'mod_sql.c' for user 'lon9man' in the authcache
2019-10-25 13:22:50,788 [3697] <auth:9>: no value found in gidcache for GID 1000: No such file or directory
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "gid2name" to module mod_sql
2019-10-25 13:22:50,788 [3697] <auth:5>: stashed name 'longman' for GID 1000 in the gidcache
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "getgroups" to module mod_sql
2019-10-25 13:22:50,788 [3697] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:50,788 [3697] <sql:19>: dispatching SQL command 'sql_select'
2019-10-25 13:22:50,788 [3697] <auth:4>: using module 'mod_sql.c' from authcache to authenticate user 'lon9man'
2019-10-25 13:22:50,788 [3697] <auth:6>: dispatching auth request "auth" to module mod_sql
2019-10-25 13:22:50,788 [3697] <sql:19>: dispatching SQL command 'sql_escapestring'
2019-10-25 13:22:50,789 [3697] <auth:4>: using module 'mod_sql.c' from authcache to authenticate user 'lon9man'
2019-10-25 13:22:50,789 [3697] <auth:6>: dispatching auth request "check" to module mod_sql

```
**Note:** similar log with empty **sql.passwd**-channel i saw in forum [https://forums.proftpd.org](https://forums.proftpd.org/smf/index.php/topic,12043.msg33669.html?PHPSESSID=qc1dqofe9gg4i07mjmo8htb3g0#msg33669)


sql.log:
```
...
2019-10-25 13:28:38,790 mod_sql/4.4[4193]: query "SELECT groupname, gid, members FROM FTPgrpTb WHERE (members = 'lon9man' OR members LIKE 'lon9
man,%' OR members LIKE '%,lon9man' OR members LIKE '%,lon9man,%')"
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: connection 'default' count is now 1
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_select
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: <<< cmd_getgroups
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: >>> cmd_auth
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_escapestring
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_open
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: connection 'default' count is now 2
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_open
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: connection 'default' count is now 1
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_escapestring
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: cache hit for user 'lon9man'
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: >>> cmd_check
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: checking password using SQLAuthType 'bcrypt'
```

**Comment by Castaglia** [comment] 2019-10-25 13:03
What does your `proftpd -V` output show?  What does your full `proftpd.conf` (minus any passwords) look like?

**Comment by lon9man** [comment] 2019-10-25 13:33
@Castaglia 
interesting difference in **sql.log** when i use `SQLAuthTypes` **crypt** and **bcrypt**.

crypt:
```
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: >>> cmd_auth
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: entering <->mysql cmd_escapestring
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: entering <->mysql cmd_open
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: connection 'default' count is now 2
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: exiting <-->mysql cmd_open
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: entering <->mysql cmd_close
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: connection 'default' count is now 1
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: exiting <-->mysql cmd_close
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: exiting <-->mysql cmd_escapestring
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: cache hit for user 'lon9man'
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: >>> cmd_check
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: checking password using SQLAuthType 'Crypt'
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: error using crypt(3): Invalid argument
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: 'Crypt' SQLAuthType handler reports failure
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: <<< cmd_check
2019-10-25 16:25:29,889 mod_sql/4.4[29860]: <<< cmd_auth
```

bcrypt:
```
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: >>> cmd_auth
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_escapestring
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_open
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: connection 'default' count is now 2
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_open
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: entering     mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: connection 'default' count is now 1
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_close
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: exiting      mysql cmd_escapestring
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: cache hit for user 'lon9man'
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: >>> cmd_check
2019-10-25 13:28:38,791 mod_sql/4.4[4193]: checking password using SQLAuthType 'bcrypt'
```

please note, that **sql.log** for **bcrypt** looks like unfinished/truncated. but for **crypt** it has error message **'Crypt' SQLAuthType handler reports failure**

**Comment by Castaglia** [comment] 2019-10-25 15:17
You have configured `mod_sql_passwd` via the `--with-shared` configure option, which means that it's a shared module -- and that means it needs to be dynamically loaded.  I don't see this anywhere in your config:
```
LoadModule mod_sql_passwd.c
```
Unless it's in your `Include /etc/proftpd/modules.conf` file?  If so, please provide that as well.  In short, I need everything you have (build and config files), so that I can attempt to reproduce the behavior locally.

**Comment by lon9man** [comment] 2019-10-25 15:21
@Castaglia 
> Unless it's in your Include /etc/proftpd/modules.conf file? 

Yes

modules.conf
```
ModulePath /usr/local/libexec

ModuleControlsACLs insmod,rmmod allow user root
ModuleControlsACLs lsmod allow user *

LoadModule mod_sql.c
LoadModule mod_sql_mysql.c
LoadModule mod_sql_passwd.c

LoadModule mod_quotatab.c
```

**Comment by araratpoghosyan** [comment] 2021-02-11 08:27
Hi @Castaglia, @lon9man 

Thank you for a great discussion, is there any news on Bcrypt support for proftpd?

Thanks in advance

**Comment by lon9man** [comment] 2021-02-11 08:38
Hi @araratpoghosyan i didn't try it anymore since my last attempts.

did you try it by yourself?
