### ISSUE TITLE
Several new bugs in 1.3.6?

### ISSUE THREAD

**Issue by chrcoluk** [proftpd/proftpd#687] opened 2018-04-13 19:26 UTC
### What I Did

Updated proftpd from 1.3.5 to 1.3.6

Now on startup this appears.
```
mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
mod_tls/2.7: unable to generate initial session ticket key: Resource temporarily unavailable
```
mod_ctrls I have not specifically enabled or configured - did find a bug report on here tho.
mod_tls - I see there is a new feature in 1.3.6, if I try to disable the feature, it makes no difference however. Plus it is supposed to be off by default anyway.

TLSSessionTickets

### What I Expected/Wanted

I expected no warnings on startup

### ProFTPD Version and Configuration
```
Compile-time Settings:
  Version: 1.3.6 (stable)
  Platform: FREEBSD10 (FREEBSD10_3) [FreeBSD 10.3-RELEASE-p12 amd64]
  Built: Fri Apr 13 2018 16:53:09 BST
  Built With:
    configure  '--localstatedir=/var/run' '--libexecdir=/usr/local/libexec/proftpd' '--with-pkgconfig=libdata/pkgconfig' '--sysconfdir=/usr/local/etc' '--enable-ctrls' '--enable-dso' '--disable-sendfile' '--enable-ipv6' '--disable-memcache' '--enable-nls' '--enable-pcre' '--disable-redis' '--with-shared=mod_ban:mod_copy:mod_ctrls_admin:mod_deflate:mod_dnsbl:mod_dynmasq:mod_exec:mod_ifsession:mod_ifversion:mod_qos:mod_quotatab:mod_quotatab_file:mod_quotatab_radius:mod_quotatab_sql:mod_radius:mod_ratio:mod_readme:mod_rewrite:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_site_misc:mod_snmp:mod_sql:mod_sql_passwd:mod_tls:mod_tls_shmcache:mod_unique_id:mod_wrap2:mod_wrap2_file:mod_wrap2_sql' '--with-includes=/usr/local/include' '--with-libraries=/usr/local/lib' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd10.3' 'build_alias=amd64-portbld-freebsd10.3' 'CC=clang39' 'CFLAGS=-O2 -pipe -fdiagnostics-color=auto -D_FORTIFY_SOURCE=2 -march=native  -DLIBICONV_PLUG -fstack-protector-strong --param ssp-buffer-size=4 -fno-strict-aliasing' 'LDFLAGS= -Wl,-z,relro -Wl,-z,now -Wl,-rpath=/usr/local/llvm39/lib -lpthread -Wl,-rpath,/usr/local/lib -fstack-protector' 'LIBS=-lssl -lcrypto -L/usr/local/lib' 'CPPFLAGS=-DHAVE_OPENSSL -I/usr/local/include -DLIBICONV_PLUG' 'CPP=clang-cpp39' 'CXX=clang++39' 'CXXFLAGS=-O2 -pipe -fdiagnostics-color=auto -D_FORTIFY_SOURCE=2 -march=native -DLIBICONV_PLUG -fstack-protector-strong --param ssp-buffer-size=4 -fno-strict-aliasing -Wno-deprecated  -DLIBICONV_PLUG'

  CFLAGS: -g2 -O2 -pipe -fdiagnostics-color=auto -D_FORTIFY_SOURCE=2 -march=native  -DLIBICONV_PLUG -fstack-protector-strong --param ssp-buffer-size=4 -fno-strict-aliasing -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib  -Wl,-z,relro -Wl,-z,now -Wl,-rpath=/usr/local/llvm39/lib -lpthread -Wl,-rpath,/usr/local/lib -fstack-protector -rdynamic -L/usr/local/lib
  LIBS: -lintl  -lpcreposix -lpcre -lssl -lcrypto -lpam -lsupp -lexecinfo -lcrypt -lssl -lcrypto -L/usr/local/lib -liconv -lutil -pthread

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    + PCRE support
    - POSIX ACL support
    - Shadow file suppport
    - Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 1024
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```
config below, only omitted vhosts
```
ServerName              "HF-Web6 11"
ServerType      standalone

Port                    21
PassivePorts        10100 12500
UseReverseDNS           off
TimesGMT                    off
TimeoutLogin            30
TimeoutIdle                 300
TimeoutNoTransfer       900
TimeoutStalled          600

AllowForeignAddress     Off
MaxConnectionRate       10

MaxInstances        150
MaxClientsPerUser       12
CommandBufferSize       512
SocketOptions           sndbuf 2048576 rcvbuf 513920
WtmpLog             off

UseIPv6                         on

IdentLookups            off
ServerIdent                     off

# Delay engine reduces impact of the so-called Timing Attack described in
# http://www.securityfocus.com/bid/11430/discuss
# It is on by default. 
<IfModule mod_delay.c>
  DelayEngine on
</IfModule>

LoadModule mod_clamav.c
<IfModule mod_clamav.c>
  ClamAV on
  ClamServer 127.0.0.1
  ClamPort 3310
</IfModule>

# Disable facts if want to force LIST to honour file perms viewable.
<IfModule mod_facts.c>
    FactsAdvertise on
    FactsOptions UseSlink
</IfModule>

ScoreboardFile                  /var/run/proftpd/proftpd.pid

TransferLog             /var/log/proftpd/xferlog.legacy
LogFormat               default "%h %l %u %t \"%r\" %s %b"
LogFormat               auth    "%v [%P] %h %t \"%r\" %s"
LogFormat               write   "%h %l %u %t \"%r\" %s %b"
LogFormat               custom   "%a %d %f %J %m %l %u %t \"%r\" %s %S %b %T %{protocol}"

#DON'T modify this log format.  It's used by DirectAdmin to determine user usage
LogFormat               userlog "%u %b %m %a"
ExtendedLog             /var/log/proftpd/148.251.4.102.bytes WRITE,READ userlog

AuthUserFile                    /etc/proftpd.passwd
DefaultServer           on
AuthOrder mod_auth_file.c

<IfModule mod_ban.c>
  BanEngine off
  BanLog /var/log/proftpd/proftpd-ban.log
  BanTable /var/db/proftpd/ban
  BanOnEvent MaxLoginAttempts 3/00:10:00 01:00:00
  BanControlsACLs all allow user admin,root,ftp
  BanMessage "Banned! [ %a ]"
</IfModule>

LoadModule mod_tls.c

<IfModule mod_tls.c>
                TLSProtocol TLSv1 TLSv1.1 TLSv1.2
                TLSDHParamFile /usr/local/etc/proftpd/dh2048.pem
</IfModule>

<Global>
        PassivePorts            10100 12500
        DeferWelcome            on

        RequireValidShell       no

        DefaultRoot             ~

        User                    ftp
        Group                   ftp

        AllowStoreRestart       on
        AllowRetrieveRestart    on

        ListOptions             -a
        ShowSymlinks            on
        <IfModule mod_facts.c>
                ##Enable this with proftpd 1.3.4b+ to fix FileZilla MLSD
                ##http://www.proftpd.org/docs/modules/mod_facts.html#FactsOptions
                FactsOptions UseSlink
        </IfModule>

        Umask                   022
        DisplayLogin            welcome.msg
        DisplayChdir            readme
        AllowOverwrite          yes
        IdentLookups            off
        ExtendedLog             /var/log/proftpd/access.log WRITE,READ write
        ExtendedLog             /var/log/proftpd/auth.log AUTH auth
        ExtendedLog             /var/log/proftpd/custom.log WRITE,READ write
        
        #
        # Paranoia logging level....
        #
        #ExtendedLog    /var/log/proftpd/paranoid.log ALL default

        <IfModule mod_tls.c>
        TLSEngine on
        TLSLog /var/log/proftpd/proftpd.tls.log
        TLSVerifyClient off
        TLSRequired auth
        TLSServerCipherPreference on
        TLSOptions  NoSessionReuseRequired NoEmptyFragments
        TLSCipherSuite ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDH+AES256:ECDH+AES128:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA:ECDH+3DES:CAMELLIA256-SHA:CAMELLIA128-SHA:ECDH+3DES:RSA+3DES:ECDHE-RSA-RC4-SHA:RC4-SHA:!aNULL:!MD5
        TLSDHParamFile /usr/local/etc/proftpd/dh2048.pem
        TLSTimeoutHandshake 30
        TLSRSACertificateFile /etc/proftpd.cert
        TLSRSACertificateKeyFile /etc/proftpd.key
        TLSRenegotiate ctrl 3600 data 25165824 required off timeout 180
        </IfModule>

        ##################################################
        # DNSBL stuff. Applies to virtualhosts as well #
        ##################################################
    <IfModule mod_dnsbl.c>
        # Turned off as it checks for every file transfer...
        DNSBLEngine off
        #DNSBLDomain sbl.spamhaus.org
        DNSBLDomain xbl.spamhaus.org
        DNSBLLog /var/log/proftpd/proftpd.dnsbl.log
        DNSBLPolicy "allow,deny"
    </IfModule>
</Global>
```

**Comment by chrcoluk** [comment] 2018-04-13 19:36
using the -nd10 flag I have some more info

using PCRE 8.40 2017-01-11
using TCP receive buffer size of 16060 bytes
using TCP send buffer size of 65536 bytes
testing Unix domain socket using S_ISFIFO
testing Unix domain socket using S_ISSOCK
using S_ISSOCK macro for Unix domain socket detection
mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

mod_tls/2.7: generating initial TLS session ticket key
ROOT PRIVS at mod_tls.c:4815
RELINQUISH PRIVS at mod_tls.c:4818
mod_tls/2.7: error locking session ticket key into memory: Resource temporarily unavailable
mod_tls/2.7: unable to generate initial session ticket key: Resource temporarily unavailable
mod_tls/2.7: scheduling new TLS session ticket key every 3600 secs

the proftpd.sock does get removed on shutdown, so the socket warning is just plain weird.

mod_tls seems to ignore the session ticket directive been disabled and I have no clue as to its reasons for failure.

**Comment by Castaglia** [comment] 2020-09-05 21:03
The "error locking session ticket key into memory: Resource temporarily unable" error is addressed by https://github.com/proftpd/proftpd/issues/1014.

I've not seen the "error: unable to bind to local socket: Address already in use" in quite a while; I'll see if I can reproduce this locally.

**Comment by chrcoluk** [comment] 2020-09-06 06:48
I suspect this might be related to the 'mod_tls_shmcache' module, I have disabled this and will let you know if it fixes the problem, I think that module is not enabled by default which might explain me been the only one.

**Comment by Castaglia** [comment] 2020-09-06 22:10
Using Vagrant, on a FreeBSD 11 box, I installed ProFTPD from ports:
```
$ sudo portsnap fetch extract
$ cd /usr/ports/ftp/proftpd/
$ sudo make install
```
And then:
```
[root@freebsd11 /usr/home/vagrant]# proftpd --configtest
Checking syntax of configuration file
Syntax check complete.
```

Thinking perhaps the "error: unable to bind to local socket: Address already in use" message might happen if ProFTPD was also running:
```
[root@freebsd11 /usr/ports/ftp/proftpd]# service proftpd start
Starting proftpd.

[root@freebsd11 /usr/home/vagrant]# proftpd --configtest
Checking syntax of configuration file
Syntax check complete.
```
I also tried:
```
proftpd --configtest -d10
```
No luck in reproducing that "Address already in use" error locally.

**Comment by Castaglia** [comment] 2020-09-26 20:47
@chrcoluk Are you still encountering these issues/errors, or have they been fixed in later ProFTPD versions?

**Comment by chrcoluk** [comment] 2020-10-14 15:02
I left the module disabled, but I can turn it back on, on one of my servers then after some weeks report back.

**Comment by Castaglia** [comment] 2020-12-20 00:50
@chrcoluk Yes, please, if that's OK.  I'd just like to know that we can close this particular ticket -- and open new tickets for any future issues that you might encounter.  Thanks!

**Comment by Castaglia** [comment] 2021-11-27 23:20
If there's nothing more to add to this ticket, I'd like to close it.

**Comment by Castaglia** [comment] 2022-02-19 18:39
Closing this ticket, since there's been no additional feedback.  Please open new tickets for any additional issues you see.  Thanks!

**Closed by Castaglia** 2022-02-19 18:39 UTC
Labels: waiting for feedback
