### ISSUE TITLE
426 Transfer aborted. Interrupted system call

### ISSUE THREAD

**Issue by xvkdev** [proftpd/proftpd#615] opened 2017-10-21 16:09 UTC
### What I Did

Happens with at least Filezilla and CuteFTP, but testing right now:
```
*** CuteFTP 9.0 - build Jun 25 2013 ***
COMMAND:>       [10/21/2017 11:43:34 AM] AUTH TLS
                [10/21/2017 11:43:36 AM] 234 AUTH TLS successful
STATUS:>        [10/21/2017 11:43:36 AM] Establishing SSL session...
STATUS:>        [10/21/2017 11:43:36 AM] Connected. Exchanging encryption keys...
                Session Cipher: 0 bit
STATUS:>        [10/21/2017 11:43:36 AM] SSL Connect time: 843 ms.
STATUS:>        [10/21/2017 11:43:36 AM] SSL encrypted session established.
COMMAND:>       [10/21/2017 11:43:36 AM] PBSZ 0
                [10/21/2017 11:43:37 AM] 200 PBSZ 0 successful
COMMAND:>       [10/21/2017 11:43:37 AM] USER xxxx
                [10/21/2017 11:43:37 AM] 331 Password required for xxxx
COMMAND:>       [10/21/2017 11:43:37 AM] PASS *****
                [10/21/2017 11:43:37 AM] 230 User xxxx logged in
STATUS:>        [10/21/2017 11:43:37 AM] Login successful.
COMMAND:>       [10/21/2017 11:43:37 AM] SYST
                [10/21/2017 11:43:37 AM] 215 UNIX Type: L8
STATUS:>        [10/21/2017 11:43:37 AM] Host type detected: Unix.
COMMAND:>       [10/21/2017 11:43:37 AM] PWD
                [10/21/2017 11:43:37 AM] 257 "/" is the current directory
STATUS:>        [10/21/2017 11:43:37 AM] Home directory: /
STATUS:>        [10/21/2017 11:43:37 AM] This site supports features.
STATUS:>        [10/21/2017 11:43:37 AM] This site supports XCRC.
STATUS:>        [10/21/2017 11:43:37 AM] This site supports SIZE.
STATUS:>        [10/21/2017 11:43:37 AM] Setting up character encoding.
COMMAND:>       [10/21/2017 11:43:37 AM] OPTS UTF8 on
                [10/21/2017 11:43:37 AM] 200 UTF8 set to on
STATUS:>        [10/21/2017 11:43:37 AM] Using UTF-8.
STATUS:>        [10/21/2017 11:43:37 AM] This site can resume broken downloads.
COMMAND:>       [10/21/2017 11:43:37 AM] CWD /xxxx
                [10/21/2017 11:43:38 AM] 250 CWD command successful
STATUS:>        [10/21/2017 11:43:38 AM] PWD skipped. Current folder: "/xxxx".
COMMAND:>       [10/21/2017 11:43:38 AM] TYPE I
                [10/21/2017 11:43:38 AM] 200 Type set to I
COMMAND:>       [10/21/2017 11:43:38 AM] PBSZ 0
                [10/21/2017 11:43:39 AM] 200 PBSZ 0 successful
COMMAND:>       [10/21/2017 11:43:39 AM] PROT P
                [10/21/2017 11:43:39 AM] 200 Protection set to Private
COMMAND:>       [10/21/2017 11:43:39 AM] PASV
                [10/21/2017 11:43:39 AM] 227 Entering Passive Mode (95,211,149,xxxx,xxxx,246).
COMMAND:>       [10/21/2017 11:43:39 AM] REST 262144
                [10/21/2017 11:43:39 AM] 350 Restarting at 262144. Send STORE or RETRIEVE to initiate transfer
COMMAND:>       [10/21/2017 11:43:39 AM] RETR xxxx.mkv
STATUS:>        [10/21/2017 11:43:39 AM] Connecting FTP data socket... xxxx:64758...
                [10/21/2017 11:43:40 AM] 150 Opening BINARY mode data connection for xxxx.mkv (1334793244 bytes)
STATUS:>        [10/21/2017 11:43:40 AM] Connected. Exchanging encryption keys...
                Session Cipher: 0 bit
STATUS:>        [10/21/2017 11:43:42 AM] SSL Connect time: 1667 ms.
STATUS:>        [10/21/2017 11:43:42 AM] SSL encrypted session established.
                [10/21/2017 11:44:00 AM] 426 Transfer aborted. Interrupted system call
```
### What I Expected/Wanted

A successful file transfer, which is hard to achieve on files longer than a few MB.

### ProFTPD Version and Configuration
```
  Version: 1.3.7rc1 (git)
  Platform: LINUX [Linux 3.16.0-4-amd64 x86_64]
  Built: Sat Oct 21 2017 17:33:57 CEST
  Built With:
    configure  '--enable-nls' '--with-modules=mod_tls:mod_readme:mod_sftp:mod_ct                                                                                                                                                                             rls_admin:mod_access_vroot:mod_digest:mod_geoip' '--enable-ctrls'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lGeoIP  -lssl  -lpam                                                                                                                                                                               -lcrypto -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```
Config is quite standard:
```
    TLSEngine on

    TLSRequired off

    # Server's certificate
    TLSRSACertificateFile (path)
    TLSRSACertificateKeyFile (path)
    TLSCertificateChainFile (path)

    TLSVerifyClient off
    TLSOptions NoSessionReuseRequired

    TLSRenegotiate required off
```

**Comment by Castaglia** [comment] 2017-10-22 20:29
Thanks! Do you happen to have any debug logging, debug level 10, to attach as well?

**Comment by xvkdev** [comment] 2017-10-22 20:36
No but I'll be happy to prepare one. What do I add to the config file to
get what you need?

**Comment by Castaglia** [comment] 2017-10-22 20:47
I usually use something like this, near the top of the config file:

    # Normal debug logging
    SystemLog /path/to/proftpd-debug.log
    DebugLevel 10

    # ...with trace logging, too, to the same file
    TraceLog /path/to/proftpd-debug.log
    Trace DEFAULT:20

See the [Debugging howto](http://www.proftpd.org/docs/howto/Debugging.html) and the [Tracing howto](http://www.proftpd.org/docs/howto/Tracing.html) for more details.

**Comment by Castaglia** [comment] 2017-10-22 20:55
@jmaggard10 -- are you seeing this behavior as well, for FTPS downloads?

**Comment by Castaglia** [comment] 2017-10-22 20:59
@xvkdev I just pushed PR #616 ; would you be able to try it out, see if it addresses this issue?  It's a stab in the dark at what the cause might be...

**Comment by xvkdev** [comment] 2017-10-22 21:48
First test looks good. Currently gathering the debug log just in case the
issue reappears.

**Comment by xvkdev** [comment] 2017-10-23 00:09
@Castaglia why was that PR rolled back? Seems to have made a difference.

**Comment by Castaglia** [comment] 2017-10-23 14:21
@xvkdev the PR wasn't rolled back; it's not yet merged, though, as I was waiting for confirmation.  I'll merge it to master (and cherry-pick/backport it to the 1.3.6 branch) later today when I have a little more free time.  I'd also like to see if I can create a regression test for this behavior...

**Comment by Castaglia** [comment] 2017-10-24 03:12
PR merged to master, and backported to the 1.3.6 branch.  Please re-open if you see this behavior crop up.  Thanks!

**Closed by Castaglia** 2017-10-24 03:12 UTC
Labels: bug

**Comment by cfsmp3** [comment] 2017-10-26 01:33
Issue seems completely fixed - all users have reported success. Thanks for fixing it!

**Comment by cfsmp3** [comment] 2017-10-26 01:33
Issue seems completely fixed. Thanks for fixing it!

**Comment by rbenzing** [comment] 2021-09-29 22:29
I am having this problem again in 2021
