### ISSUE TITLE
Issues with Client version to OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016

### ISSUE THREAD

**Issue by warpspeed6** [proftpd/proftpd#426] opened 2017-02-19 22:02 UTC
### What I Did
Upgrading Client version to OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
It breaks 

```
anshu@warpy:~/ProftpdC2$ sftp anshusftp12@anshu-sftp.syd.dev.messagemedia.com 
Connection to anshu-sftp.syd.dev.messagemedia.com closed by remote host.
Couldn't read packet: Connection reset by peer
anshu@warpy:~/ProftpdC2$ 

```

### What I Expected/Wanted
Proftpd to connect/behave the same. It works fine on OpenSSH_6.6.1p1, OpenSSL 1.0.1k-fips 8 Jan 2015
It does appear that openssl version might need an upgrade but logs are not sufficient yet to warrant that. 

### ProFTPD Version and Configuration
I am attaching logs/configs for this with debugs/traces enabled. 

[ConfFile.txt](https://github.com/proftpd/proftpd/files/786249/ConfFile.txt)
[versions.txt](https://github.com/proftpd/proftpd/files/786250/versions.txt)

**Comment by warpspeed6** [comment] 2017-02-19 22:20
[ClientDebugOpen7.2.txt](https://github.com/proftpd/proftpd/files/786259/ClientDebugOpen7.2.txt)
[ServerDebugTrace10.txt](https://github.com/proftpd/proftpd/files/786260/ServerDebugTrace10.txt)

**Comment by Castaglia** [comment] 2017-02-19 22:41
This looks like a duplicate of [Bug #4287](http://bugs.proftpd.org/show_bug.cgi?id=4287); see also Issue #408 .

**Comment by warpspeed6** [comment] 2017-02-19 22:51
Confirmed duplicate of https://github.com/proftpd/proftpd/issues/408

**Comment by Castaglia** [comment] 2017-02-19 22:57
Excellent.  I'm hoping to release 1.3.6-stable soon; at the same time, I'll release 1.3.5e with this fix in it.  Hopefully it can wait for that long...

**Closed by Castaglia** 2017-02-19 22:57 UTC
Labels: duplicate
