### ISSUE TITLE
Libressl support

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#361] opened 2016-12-06 13:14 UTC
### What I Did

Tried compiling Proftpd in Alpine:Edge which uses Libressl as a default
 
### What I Expected/Wanted

Proftpd compiles/operates in the same manner with Libressl as Openssl

### ProFTPD Version and Configuration

This is based on the latest source in Github

**Comment by Castaglia** [comment] 2016-12-06 16:51
This is going to require a fair amount of work; Libressl does not support the same functionality as OpenSSL, which, in turn, means that supporting libressl may result in *less* functionality in _e.g._ `mod_sftp`, `mod_tls`, `mod_sql_passwd`, _etc etc_.

For the record, I brought up an Alpine Edge (3.4) VM using Vagrant:

    Vagrant.configure("2") do |config|
      config.vm.box = "maier/alpine-3.4-x86_64"

      # Make sure the /etc/apk/repositories file contains:
      #
      # $ cat /etc/apk/repositories
      # http://dl-cdn.alpinelinux.org/alpine/v3.4/main
      # http://dl-cdn.alpinelinux.org/alpine/edge/main
      # http://dl-6.alpinelinux.org/alpine/edge/community
      #
      # After installing vim, then do `sudo apk update`.

      config.vm.provision "shell", inline: <<-SHELL
        apk update
        apk add git gdb make git vm build-base
        apk add libressl-dev
      SHELL
    end

And then, after cloning the `proftpd` GitHub repo and configuring it:

    $ ./configure --with-modules=mod_sftp:mod_tls

I encountered the following build errors:

```
gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include  -g2 -O2 -Wall -fno-omit-frame-pointer -c mod_tls.c
mod_tls.c: In function 'get_dh':
mod_tls.c:102:7: warning: implicit declaration of function 'DH_set0_pqg' [-Wimplicit-function-declaration]
   if (DH_set0_pqg(dh, p, NULL, g) != 1) {
       ^
mod_tls.c: In function 'read_cert':
mod_tls.c:120:34: warning: implicit declaration of function 'SSL_CTX_get_default_passwd_cb' [-Wimplicit-function-declaration]
   cert = PEM_read_X509(fh, NULL, SSL_CTX_get_default_passwd_cb(ssl_ctx),
                                  ^
mod_tls.c:121:5: warning: implicit declaration of function 'SSL_CTX_get_default_passwd_cb_userdata' [-Wimplicit-function-declaration]
     SSL_CTX_get_default_passwd_cb_userdata(ssl_ctx));
     ^
mod_tls.c:120:34: warning: passing argument 3 of 'PEM_read_X509' makes pointer from integer without a cast [-Wint-conversion]
   cert = PEM_read_X509(fh, NULL, SSL_CTX_get_default_passwd_cb(ssl_ctx),
                                  ^
In file included from /usr/include/openssl/ssl.h:150:0,
                 from ../include/mod_tls.h:32,
                 from mod_tls.c:39:
/usr/include/openssl/pem.h:432:1: note: expected 'int (*)(char *, int,  int,  void *)' but argument is of type 'int'
 DECLARE_PEM_rw(X509, X509)
 ^
mod_tls.c:121:5: warning: passing argument 4 of 'PEM_read_X509' makes pointer from integer without a cast [-Wint-conversion]
     SSL_CTX_get_default_passwd_cb_userdata(ssl_ctx));
     ^
In file included from /usr/include/openssl/ssl.h:150:0,
                 from ../include/mod_tls.h:32,
                 from mod_tls.c:39:
/usr/include/openssl/pem.h:432:1: note: expected 'void *' but argument is of type 'int'
 DECLARE_PEM_rw(X509, X509)
 ^
mod_tls.c: In function 'tls_info_cb':
mod_tls.c:826:12: error: 'TLS_ST_OK' undeclared (first use in this function)
       case TLS_ST_OK:
            ^
mod_tls.c:826:12: note: each undeclared identifier is reported only once for each function it appears in
mod_tls.c:850:22: error: 'TLS_ST_SR_CLNT_HELLO' undeclared (first use in this function)
     if (ssl_state == TLS_ST_SR_CLNT_HELLO) {
                      ^
mod_tls.c: In function 'tls_dotlogin_allow':
mod_tls.c:7135:5: warning: implicit declaration of function 'X509_get0_signatur' [-Wimplicit-function-declaration]
     X509_get0_signature(&client_sig, NULL, client_cert);
     ^
mod_tls.c: In function 'tls_verify_crl':
mod_tls.c:8168:10: warning: implicit declaration of function 'X509_STORE_CTX_get1_crls' [-Wimplicit-function-declaration]
   crls = X509_STORE_CTX_get1_crls(store_ctx, subject);
          ^
mod_tls.c:8168:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   crls = X509_STORE_CTX_get1_crls(store_ctx, subject);
        ^
mod_tls.c:8266:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   crls = X509_STORE_CTX_get1_crls(store_ctx, subject);
        ^
mod_tls.c:8288:14: warning: implicit declaration of function 'X509_REVOKED_get0_serialNumber' [-Wimplicit-function-declaration]
         sn = X509_REVOKED_get0_serialNumber(revoked);
              ^
mod_tls.c:8288:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         sn = X509_REVOKED_get0_serialNumber(revoked);
            ^
mod_tls.c: In function 'tls_verify_ocsp_url':
mod_tls.c:8553:11: warning: implicit declaration of function 'X509_STORE_CTX_get0_store' [-Wimplicit-function-declaration]
   store = X509_STORE_CTX_get0_store(ctx);
           ^
mod_tls.c:8553:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   store = X509_STORE_CTX_get0_store(ctx);
         ^
mod_tls.c: In function 'tls_sess_init':
mod_tls.c:13664:9: warning: implicit declaration of function 'SSL_CTX_use_serverinfo_file' [-Wimplicit-function-declaration]
     if (SSL_CTX_use_serverinfo_file(ssl_ctx, path) != 1) {

```

Addressing this will require a fair amount of Autoconf work.  And the above is just for `mod_tls`.  For `mod_sftp`, using `./configure --with-modules=mod_sftp`, it's a different set of errors.  Many of which are caused by the code _trying_ to handle the OpenSSL-1.0.x to OpenSSL-1.1.x API transition, based on the OpenSSL version number (which, of course, Libressl does *not* change).  Sigh.

**Comment by tspicer** [comment] 2016-12-06 17:38
i got the same errors. For now I'm using Alpine 3.4. I figured it was going to be a cluster : (

I'm not sure what the trend lines are in relation to openssl, libressl,... adoption. Maybe this becomes more of an issue at a later date?

I guess the option for Alpine would be to swap out libressl or compile openssl.

**Comment by vaygr** [comment] 2017-01-15 04:12
Tried building `1.3.5c` against LibreSSL 2.1 branch on OpenBSD, got this:

```text
cc -I/usr/local/include -DHAVE_CONFIG_H  -DOPENBSD5_7 -DOPENBSD5 -I.. -I../include  -O2 -pipe -Wall -c mod_tls.c
mod_tls.c: In function 'get_dh':
mod_tls.c:100: warning: implicit declaration of function 'DH_set0_pqg'
mod_tls.c: In function 'read_cert':
mod_tls.c:118: warning: implicit declaration of function 'SSL_CTX_get_default_passwd_cb'
mod_tls.c:119: warning: implicit declaration of function 'SSL_CTX_get_default_passwd_cb_userdata'
mod_tls.c:119: warning: passing argument 3 of 'PEM_read_X509' makes pointer from integer without a cast
mod_tls.c:119: warning: passing argument 4 of 'PEM_read_X509' makes pointer from integer without a cast
mod_tls.c: In function 'tls_diags_cb':
mod_tls.c:613: error: 'TLS_ST_OK' undeclared (first use in this function)
mod_tls.c:613: error: (Each undeclared identifier is reported only once
mod_tls.c:613: error: for each function it appears in.)
mod_tls.c:637: error: 'TLS_ST_SR_CLNT_HELLO' undeclared (first use in this function)
mod_tls.c: In function 'tls_init_ctx':
mod_tls.c:2874: warning: passing argument 2 of 'SSL_CTX_sess_set_get_cb' from incompatible pointer type
mod_tls.c: In function 'tls_dotlogin_allow':
mod_tls.c:4841: warning: implicit declaration of function 'X509_get0_signature'
mod_tls.c: In function 'tls_verify_crl':
mod_tls.c:5890: warning: implicit declaration of function 'X509_STORE_CTX_get1_crls'
mod_tls.c:5890: warning: assignment makes pointer from integer without a cast
mod_tls.c:5987: warning: assignment makes pointer from integer without a cast
mod_tls.c:6009: warning: implicit declaration of function 'X509_REVOKED_get0_serialNumber'
mod_tls.c:6009: warning: assignment makes pointer from integer without a cast
mod_tls.c: In function 'tls_verify_ocsp_url':
mod_tls.c:6375: warning: implicit declaration of function 'X509_STORE_CTX_get0_store'
mod_tls.c:6375: warning: assignment makes pointer from integer without a cast
mod_tls.c: In function 'tls_sess_cache_get_sess_cb':
mod_tls.c:7107: warning: passing argument 2 of 'tls_sess_cache->get' discards qualifiers from pointer target type
```

**Comment by vakartel** [comment] 2017-01-16 14:23
@tspicer 
Hi, I made a testing/proftpd PR. https://github.com/alpinelinux/aports/pull/753
I'll be glad if you test it.

**Comment by tspicer** [comment] 2017-01-16 15:11
@ vakartel Is this just for mod_tls? Any implications  or exepctations relating to mod_sftp?

**Comment by vakartel** [comment] 2017-01-16 15:18
@tspicer 
I fix the only mod_tls  build errors.
- error: 'TLS_ST_OK' undeclared (first use in this function)
- error: 'TLS_ST_SR_CLNT_HELLO' undeclared (first use in this function)

 mod_sftp builds fine.

**Comment by vaygr** [comment] 2017-01-16 16:00
Well, if *ifdef magic* was the only thing made after **1.3.5b**, then the following one-liner fixed building and linking **1.3.5d** for me (Makefile syntax):

```makefile
@perl -pi -e "s:#\s*if OPENSSL_VERSION_NUMBER >= 0x10100000LL?:#if OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined LIBRESSL_VERSION_NUMBER:;s:#\s*if OPENSSL_VERSION_NUMBER < 0x10100000LL?:#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined LIBRESSL_VERSION_NUMBER:" \
               ${WRKSRC}/contrib/mod_tls.c \
               ${WRKSRC}/contrib/mod_sftp/{mac,kex,keys,crypto}.c
```

But unfortunately the very first sftp login leads to a segfault:

```
Jan 16 18:50:43 <none> proftpd[10320]: 0.0.0.0 (X.X.X.X[X.X.X.X]) - ProFTPD terminating (signal 11) 
```

**Comment by vakartel** [comment] 2017-01-17 14:07
@vaygr it was enough for compiling bun not for successful loading.

I tried to compile mod_tls, mod_tls_shmcache and mod_sftp as static modules and make a big patch to resolve all external references.

Unfortunately it not applies on this git, it's for 1.3.5b only.

you can see it at https://github.com/alpinelinux/aports/pull/753/commits/480fa77d59e84f8ae67784d8fdbc17c3f498215a

**Comment by Castaglia** [comment] 2017-02-16 04:31
@tspicer @vakartel could you confirm that building with PR #421, ProFTPD (and mod_tls, and mod_sftp, _et al_) function properly?

**Comment by Castaglia** [comment] 2017-02-16 06:58
This should now be fixed in master, as PR #421 has been merged.  (I tested the basics of it via Vagrant.)

**Closed by Castaglia** 2017-02-16 06:58 UTC
Labels: enhancement

**Comment by vakartel** [comment] 2017-02-19 11:40
@Castaglia, I confirm it builds and works well. I can connect to proftpd-sftp via openssh sftp client. It authenticates me by key-pair and I can download file. 
But the sftp> prompt shows in a strange way

`$ **sftp -P 2222 localhost**

Connected to localhost.

**ls**

sftp>              abuild                abuild-php-extension  anew                  aold                  
apkbuild-pecl         aports                aports.old            bin                   git_php7              github-squash     
oci                   packages              x86                   

**bye**

sftp> alpine:~/vakartel/aports/testing/proftpd$ `

**Comment by Castaglia** [comment] 2017-02-19 14:33
Which version of OpenSSH are you using?  The change to LibreSSL should not have affected any of the SFTP-level formatting like; I suspect something else is involved.

**Comment by vakartel** [comment] 2017-02-19 17:13
$ ssh -V
OpenSSH_7.4p1, LibreSSL 2.4.5

**Comment by Castaglia** [comment] 2017-02-19 23:25
@vakartel Hrm.  Using libressl-2.5.1 (compiled from source), the latest proftpd (compiled from source), and OpenSSH 7.4p1 (compiled from source), the `sftp` interaction appears normal for me; this is on an Ubuntu 14.04 LTS VM:
```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-105-generic #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vakartel** [comment] 2017-02-20 09:55
@Castaglia 
I tried to connect to sftp from ubuntu and all looks fine. So the prompt bug is an alpinelinux local...
