### ISSUE TITLE
SystemLog setting ignored?

### ISSUE THREAD

**Issue by xjobex** [proftpd/proftpd#1017] opened 2020-05-19 15:20 UTC
Hi, I am running proftpd (proftpd-1.3.6c-1.el8.x86_64) on CentOS8 and set `SystemLog   /var/log/proftpd/proftpd.log` in proftpd.conf, but this file remains empty. xferlog is normally populated. Am I configuring something wrong? 

### ProFTPD Version and Configuration

```bash
[root@ftp etc]# proftpd -V
Compile-time Settings:
  Version: 1.3.6c (maint)
  Platform: LINUX [Linux 4.18.0-147.8.1.el8_1.x86_64 x86_64]
  Built: Wed Feb 19 2020 15:29:57 UTC
  Built With:
    configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--disable-pcre' '--disable-redis' '--enable-shadow' '--enable-tests=nonetwork' '--with-libraries=/usr/lib64/mariadb' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'

  CFLAGS: -g2 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic -L/usr/lib64/mariadb -L/usr/lib64/ -L/usr/lib64
  LIBS: -lacl  -lssl -lcrypto -lcap  -lssl -lcrypto  -lpam -lsupp -lattr -lresolv -lresolv -lcrypt -ldl -lmemcachedutil -lmemcached

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support (FIPS enabled)
    - PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

```

```
[root@ftp etc]# cat proftpd.conf

Include /etc/proftpd/modules.conf

ServerName                      "company-branch ftps server"
ServerIdent                     off
DefaultServer                   on
UseIPv6                         off
PassivePorts                    40000 40019

ServerType                      standalone
DeferWelcome                    on

DisplayLogin                    /home/ftp/welcome.msg
DisplayChdir                    .message true
ListOptions                     "-l"

DenyFilter                      \*.*/

UseReverseDNS                   off

IdentLookups                    off

MaxInstances                    150

UseSendfile                     off

LogFormat                       default "%h %l %u %t \"%r\" %s %b"
LogFormat                       auth    "%v [%P] %h %t \"%r\" %s"

ControlsEngine                  off
ControlsACLs                    all allow user root
ControlsSocketACL               allow user *
ControlsLog                     /var/log/proftpd/controls.log

<IfModule mod_ctrls_admin.c>
  AdminControlsEngine           off
</IfModule>

<IfModule mod_vroot.c>
  VRootEngine                   on
</IfModule>

<IfDefine TLS>
Include /etc/proftpd/mod_tls.conf
</IfDefine>

<IfModule mod_ban.c>
Include /etc/proftpd/mod_ban.conf
</IfModule>

<IfModule mod_qos.c>
Include /etc/proftpd/mod_qos.conf
</IfModule>

TransferLog /var/log/proftpd/xferlog
SystemLog   /var/log/proftpd/proftpd.log

<Global>

DefaultRoot                     ~ !adm

AuthOrder                       mod_ldap.c
RequireValidShell               off

<IfModule mod_ldap.c>
  # LDAPUseTLS on
  LDAPServer ldap://192.168.1.10/??sub
  LDAPUsers ou=ftp,dc=company
</IfModule>

PersistentPasswd                off

User                            nobody
Group                           nobody

Umask                           002     022

AllowOverwrite          yes
<Limit ALL SITE_CHMOD>
  AllowAll
</Limit>

</Global>

<IfDefine ANONYMOUS_FTP>
Include /etc/proftpd/anonftp.conf
</IfDefine>

<IfModule mod_sftp.c>
 <VirtualHost 0.0.0.0>
  Port 22
  SFTPEngine on
  SFTPLog /var/log/proftpd/sftp.log
  SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u
  SFTPOptions InsecureHostKeyPerms
  SFTPHostKey /etc/ssh/ssh_host_ecdsa_key
  SFTPHostKey /etc/ssh/ssh_host_rsa_key
 </VirtualHost>
</IfModule>

Include /etc/proftpd/conf.d/*.conf

```

**Comment by Castaglia** [comment] 2020-05-20 02:27
What does `proftpd -nd10` show?  Are there any warnings/errors when ProFTPD is started?  Note that to see these, you may need to start ProFTPD manually, _not_ using any init/systemd start scripts.

**Comment by xjobex** [comment] 2020-05-22 14:35
Hi, I attached the output of `proftpd -nd10` command, with ProFTPD service startup and a file transfer. I started ProFTPD manually as root from command line; proftpd.log does not get written.
[proftpd.debug.log](https://github.com/proftpd/proftpd/files/4668646/proftpd.debug.log)

**Comment by Castaglia** [comment] 2020-05-23 15:35
Hmm.  Curious.  What does the following command show?
```
$ ls -aln /var /var/log /var/log/proftpd /var/log/proftpd/proftpd.log
```

**Comment by xjobex** [comment] 2020-05-25 09:11
Here is the output of that command:

```Shell
ls -aln /var /var/log /var/log/proftpd /var/log/proftpd/proftpd.log
-rw-r-----   1 0 0    0 Apr 28 10:36 /var/log/proftpd/proftpd.log

/var:
total 12
drwxr-xr-x. 20 0 0  278 Sep 30  2019 .
dr-xr-xr-x. 19 0 0  275 Oct 14  2019 ..
drwxr-xr-x.  2 0 0    6 May 11  2019 adm
drwxr-xr-x.  8 0 0   94 Oct 30  2019 cache
drwxr-xr-x.  2 0 0    6 Apr  9 21:01 crash
drwxr-xr-x.  3 0 0   18 Sep 30  2019 db
drwxr-xr-x.  3 0 0   18 Sep 30  2019 empty
drwxr-xr-x.  4 0 0   51 Feb 19 16:30 ftp
drwxr-xr-x.  2 0 0    6 May 11  2019 games
drwxr-xr-x.  2 0 0    6 May 11  2019 gopher
drwxr-xr-x.  3 0 0   18 Nov  8  2019 kerberos
drwxr-xr-x. 29 0 0 4096 Apr 20 13:48 lib
drwxr-xr-x.  2 0 0    6 May 11  2019 local
lrwxrwxrwx.  1 0 0   11 Sep 30  2019 lock -> ../run/lock
drwxr-xr-x.  9 0 0 4096 May 23 16:08 log
lrwxrwxrwx.  1 0 0   10 May 11  2019 mail -> spool/mail
drwxr-xr-x.  2 0 0    6 May 11  2019 nis
drwxr-xr-x.  2 0 0    6 May 11  2019 opt
drwxr-xr-x.  2 0 0    6 May 11  2019 preserve
lrwxrwxrwx.  1 0 0    6 Sep 30  2019 run -> ../run
drwxr-xr-x.  7 0 0   71 Apr 20 13:48 spool
drwxrwxrwt.  4 0 0  164 Apr 27 12:18 tmp
-rw-r--r--.  1 0 0  208 Sep 30  2019 .updated
drwxr-xr-x.  2 0 0    6 May 11  2019 yp

/var/log:
total 79656
drwxr-xr-x.  9   0   0     4096 May 23 16:08 .
drwxr-xr-x. 20   0   0      278 Sep 30  2019 ..
drwxr-xr-x.  2   0   0      280 Sep 30  2019 anaconda
drwx------.  2   0   0       23 Jan  3 17:49 audit
-rw-rw----.  1   0  22     6912 May 25 11:06 btmp
drwxr-xr-x.  2 996 993        6 Nov 19  2019 chrony
-rw-r--r--.  1   0   0 74026313 Jan 28 10:27 dnf.librepo.log
-rw-r--r--   1   0   0    60387 May 25 10:59 dnf.log
-rw-r--r--   1   0   0  1048555 May 23 16:08 dnf.log.1
-rw-r--r--   1   0   0  1048523 Apr 20 23:21 dnf.log.2
-rw-r--r--   1   0   0  1048517 Mar 20 12:11 dnf.log.3
-rw-r--r--   1   0   0  1042500 Feb 20 10:58 dnf.log.4
-rw-r--r--.  1   0   0   432459 May 25 10:59 dnf.rpm.log
-rw-r-----.  1   0   0   208965 May  4 10:18 firewalld
-rw-r--r--.  1   0   0  2294507 May 25 10:59 hawkey.log
-rw-rw-r--.  1   0  22   291708 May 25 11:06 lastlog
drwx------.  2   0   0        6 Sep 30  2019 private
drwxr-x---.  2   0   0      170 Apr 28 11:37 proftpd
-rw-r--r--   1   0   0     1040 Apr  9 23:51 README
drwxr-x---.  2 997 994       93 Apr 13 19:09 sssd
drwxr-xr-x.  2   0   0       23 Feb  4 16:59 tuned
-rw-------.  1   0   0      719 Oct 14  2019 vmware-network.log
-rw-------.  1   0   0    11228 Apr 17 15:50 vmware-vgauthsvc.log.0
-rw-------.  1   0   0    11760 Apr 17 15:50 vmware-vmsvc.log
-rw-rw-r--.  1   0  22   186240 May 25 11:06 wtmp
-rw-r--r--.  1   0   0    67758 Oct 22  2019 xferlog

/var/log/proftpd:
total 340
drwxr-x---. 2 0 0    170 Apr 28 11:37 .
drwxr-xr-x. 9 0 0   4096 May 23 16:08 ..
-rw-r-----. 1 0 0      0 Oct 14  2019 controls.log
-rw-r--r--  1 0 0  71601 May 19 17:06 extended.log
-rw-r-----. 1 0 0      0 Oct 14  2019 ftpd.log
-rw-r--r--  1 0 0   9232 Apr 28 11:59 paranoid.log
-rw-r-----  1 0 0      0 Apr 28 10:36 proftpd.log
-rw-r-----. 1 0 0 189501 May 25 10:56 sftp.log
-rw-r-----  1 0 0  54103 May 22 16:28 tls.log
-rw-r--r--  1 0 0   4628 May 22 16:28 xferlog
-rw-r--r--  1 0 0      0 Apr 28 11:37 xferlog.ftpsimc

```

**Comment by Castaglia** [comment] 2020-05-25 16:38
Thanks!  The trailing `.` at the end of the listing for _e.g._ `/var`, `/var/log`, `/var/log/proftpd` indicate an SELinux security context, per this [StackOverflow post](https://superuser.com/questions/230559/what-does-the-dot-mean-at-the-end-of-rw-r-r-how-do-you-set-it-with-chmod).  That being the case, what do the following commands show?
```
$ ls -Z /var /var/log /var/log/proftpd
$ lsattr -l /var /var/log /var/log/proftpd
```

**Comment by xjobex** [comment] 2020-05-28 08:43
Hi, first of all I point out that selinux is disabled on that server:
```shell
[root@ftp ~]# sestatus
SELinux status:                 disabled
[root@ftp ~]#
```

This is the output of the two commands:
```shell
[root@ftp ~]# ls -Z /var /var/log /var/log/proftpd
/var:
           system_u:object_r:var_t:s0 adm               system_u:object_r:var_t:s0 gopher               system_u:object_r:var_t:s0 nis
           system_u:object_r:var_t:s0 cache             system_u:object_r:var_t:s0 kerberos             system_u:object_r:var_t:s0 opt
   system_u:object_r:kdump_crash_t:s0 crash         system_u:object_r:var_lib_t:s0 lib                  system_u:object_r:var_t:s0 preserve
     system_u:object_r:system_db_t:s0 db                system_u:object_r:var_t:s0 local            system_u:object_r:var_run_t:s0 run
           system_u:object_r:var_t:s0 empty        system_u:object_r:var_lock_t:s0 lock           system_u:object_r:var_spool_t:s0 spool
system_u:object_r:public_content_t:s0 ftp           system_u:object_r:var_log_t:s0 log                  system_u:object_r:tmp_t:s0 tmp
    system_u:object_r:games_data_t:s0 games      system_u:object_r:mail_spool_t:s0 mail              system_u:object_r:var_yp_t:s0 yp

/var/log:
          system_u:object_r:var_log_t:s0 anaconda                   system_u:object_r:lastlog_t:s0 lastlog
       system_u:object_r:auditd_log_t:s0 audit                      system_u:object_r:var_log_t:s0 private
          system_u:object_r:faillog_t:s0 btmp                       system_u:object_r:xferlog_t:s0 proftpd
  system_u:object_r:chronyd_var_log_t:s0 chrony                                                  ? README
      unconfined_u:object_r:var_log_t:s0 dnf.librepo.log       system_u:object_r:sssd_var_log_t:s0 sssd
                                       ? dnf.log                  system_u:object_r:tuned_log_t:s0 tuned
                                       ? dnf.log.1                  system_u:object_r:var_log_t:s0 vmware-network.1.log
                                       ? dnf.log.2                                               ? vmware-network.log
                                       ? dnf.log.3               system_u:object_r:vmware_log_t:s0 vmware-vgauthsvc.log.0
                                       ? dnf.log.4               system_u:object_r:vmware_log_t:s0 vmware-vmsvc.log
      unconfined_u:object_r:var_log_t:s0 dnf.rpm.log                   system_u:object_r:wtmp_t:s0 wtmp
system_u:object_r:firewalld_var_log_t:s0 firewalld                  system_u:object_r:xferlog_t:s0 xferlog
      unconfined_u:object_r:var_log_t:s0 hawkey.log

/var/log/proftpd:
system_u:object_r:xferlog_t:s0 controls.log                               ? paranoid.log                               ? tls.log
                             ? extended.log                               ? proftpd.log                                ? xferlog
system_u:object_r:xferlog_t:s0 ftpd.log      system_u:object_r:xferlog_t:s0 sftp.log                                   ? xferlog.ftp
```

```shell
[root@ftp ~]# lsattr -l /var /var/log /var/log/proftpd
/var/lib                     ---
lsattr: Operation not supported While reading flags on /var/run
lsattr: Operation not supported While reading flags on /var/lock
/var/log                     ---
/var/adm                     ---
/var/cache                   ---
/var/db                      ---
/var/empty                   ---
/var/ftp                     ---
/var/games                   ---
/var/gopher                  ---
/var/local                   ---
lsattr: Operation not supported While reading flags on /var/mail
/var/nis                     ---
/var/opt                     ---
/var/preserve                ---
/var/spool                   ---
/var/tmp                     ---
/var/yp                      ---
/var/kerberos                ---
/var/crash                   ---
/var/log/lastlog             ---
/var/log/README              ---
/var/log/private             ---
/var/log/wtmp                ---
/var/log/btmp                ---
/var/log/sssd                ---
/var/log/tuned               ---
/var/log/chrony              ---
/var/log/audit               ---
/var/log/anaconda            ---
/var/log/firewalld           ---
/var/log/dnf.librepo.log     ---
/var/log/dnf.rpm.log         ---
/var/log/hawkey.log          ---
/var/log/vmware-vgauthsvc.log.0 ---
/var/log/vmware-vmsvc.log    ---
/var/log/proftpd             ---
/var/log/xferlog             ---
/var/log/dnf.log.4           ---
/var/log/dnf.log.3           ---
/var/log/dnf.log.2           ---
/var/log/dnf.log.1           ---
/var/log/dnf.log             ---
/var/log/vmware-network.1.log ---
/var/log/vmware-network.log  ---
/var/log/proftpd/controls.log ---
/var/log/proftpd/ftpd.log    ---
/var/log/proftpd/sftp.log    ---
/var/log/proftpd/xferlog     ---
/var/log/proftpd/tls.log     ---
/var/log/proftpd/extended.log ---
/var/log/proftpd/proftpd.log ---
/var/log/proftpd/paranoid.log ---
/var/log/proftpd/xferlog.ftp ---
```

**Comment by jamdev12** [comment] 2021-02-14 21:57
This issue seems to be happening for ProFTPD versions 1.3.6 and 1.3.7 exclusively. I have gone ahead and compiled 1.3.5e, 1.3.6e and 1.3.7a all on the same CentOS 7.8 instance and with the same configuration running on all 3 versions, the 1.3.5e is the only one that honors the ServerLog and SFTPLog options under VirtualHost. 

What is odd though is that all three do honor the WrapLog option. SELinux is off on the CentOS 7.8 server, so I know it isn't that. The files are created, but nothing is ever logged to them. 

This issue affects the ability for fail2ban to properly find malicious attempts at brute forcing into the service. At this moment, we cannot move from 1.3.5e to any later version of the product.

Below is the config used across all 3 versions:

    DefaultServer off
    UseReverseDNS off
    User ftp
    Group ftp
    MaxInstances 5000
    UseSendfile off
    UseIPv6 off
    LogFormat default	"%h %l %u %t \"%r\" %s %b"
    SystemLog /var/log/proftpd/proftpd.log
    Port 0
    TimeoutIdle 900
    TimeoutNoTransfer 900
    AllowOverwrite on
    PassivePorts 60000 65534
    TimesGMT Off
    SetEnv TZ :/etc/localtime
    LoadModule mod_ctrls_admin.c
    LoadModule mod_sftp.c
    LoadModule mod_sftp_pam.c
    LoadModule mod_site_misc.c
    LoadModule mod_wrap2.c
    LoadModule mod_wrap2_file.c
    #LoadModule mod_wrap2_sql.c
    LoadModule mod_vroot.c
    <Global>
      ServerIdent On "FTP Server Ready"
      RootLogin off
      Umask 0003
      AllowOverwrite yes
      <Limit ALL SITE_CHMOD>
        AllowAll
      </Limit>
    SiteMiscEngine on
    </Global>
      <IfModule mod_ctrls_admin.c>
         AdminControlsEngine off
      </IfModule>
      <IfModule mod_vroot.c>
            VRootEngine on
            VRootAlias /etc/security/pam_env.conf etc/security/pam_env.conf
      </IfModule>
      <IfModule mod_sftp.c>
        <VirtualHost 1.2.3.4>
          DefaultRoot  ~
          Umask 0003
          SyslogLevel info
          ServerLog /var/log/proftpd/proftpd-vhost.log
          <Limit LOGIN>
                AllowGroup AND sftpusers,!partners
          </Limit>
          SFTPEngine on
          SFTPOptions IgnoreSFTPUploadPerms
          SFTPLog /var/log/proftpd/sftp.log
          Port 2222
          SFTPHostKey /etc/ssh/ssh_host_rsa_key
          SFTPHostKey /etc/ssh/ssh_host_ecdsa_key
          SFTPAuthorizedUserKeys file:/etc/proftpd/conf.d/auth_keys/%u_auth_keys
          SFTPCompression delayed
          MaxClientsPerUser 50
          MaxLoginAttempts 6
          SFTPClientMatch ".*J2SSH_Maverick.*" channelWindowSize 32MB
          SFTPClientMatch .* sftpProtocolVersion 3 channelWindowSize 1GB
          SFTPCiphers aes128-ctr aes192-ctr aes256-ctr
          SFTPDigests hmac-sha2-256 hmac-sha2-512 hmac-ripemd160 umac-64@openssh.com
          WrapEngine on
          WrapUserTables * file:/etc/proftpd/conf.d/user_acls/%U.allow file:/etc/proftpd/conf.d/hosts.deny
          WrapAllowMsg "Welcome to the SFTP service."
          WrapDenyMsg "User denied by access rules."
          WrapLog    /var/log/proftpd/wrap.log
        </VirtualHost>
      </IfModule>
    </IfDefine>

**Comment by Castaglia** [comment] 2021-03-06 20:25
I am wondering if this change in `SystemLog` content is due to [Bug #3983](http://bugs.proftpd.org/show_bug.cgi?id=3983).  To test this, @xjobex @jamdev12 could you add the following to your configurations, and see if it restores the expected behavior?
```
SyslogLevel DEBUG
```

**Comment by Castaglia** [comment] 2021-11-27 23:18
If there's nothing more to add to this ticket, I'd like to close it.  This particular `SystemLog` question has been added as a FAQ to the [`mod_log` docs](http://www.proftpd.org/docs/modules/mod_log.html#FAQ).

**Comment by Castaglia** [comment] 2022-02-19 18:42
Closing this ticket due to lack of activity.  Please open new tickets for any issues going forward.  Thanks!

**Closed by Castaglia** 2022-02-19 18:42 UTC
Labels: configuration, waiting for feedback
