### ISSUE TITLE
MaxStoreFileSize for single user not properly honored for SFTP uploads

### ISSUE THREAD

**Issue by DanielWozniak94** [proftpd/proftpd#1686] opened 2023-06-22 19:52 UTC
### What I Did

I'm trying to set maxstorefilesize for a specific user so I added the following
```
MaxStoreFileSize 10 Mb user restricted-user
MaxStoreFileSize *
```
However, all users end up getting restricted to 10Mb.

I am using mod_vroot as well as mod_sql, so not sure if that is having any affect on trying to set the max file size

### What I Expected/Wanted

I'm expecting only the restricted-user to have a limit set on its max file size it could upload.

### ProFTPD Version and Configuration

Version: 1.3.7f

Config File:
```
ServerName "My server" # set server name
ServerIdent Off # Hide ProFTP version

User root
Group root

#<IfDefine TLS> # Disable FTPS by commenting these lines out
#Include /etc/proftpd/mod_tls.conf
#</IfDefine>
ControlsSocket /var/run/proftpd.sock
ScoreboardFile /var/proftpd.scoreboard
PidFile /var/proftpd.pid

###############################################
# Optional:
UseIPv6 off # Turn off IPv6 if not needed
MasqueradeAddress x.x.x.x # Masq the FTP server address as its public IP

<IfModule mod_vroot.c>
  VRootEngine on
</IfModule>

# Only allow users to upload files, all other permissions are denied.
# The monitor user is a special case which also has the ability 
# to list files.
<Directory />
  <Limit LIST>
    AllowGroup monitors
    DenyAll
  </Limit>
  <Limit STOR>
    AllowAll
  </Limit>
</Directory>

MaxStoreFileSize 10 Mb user restricted-user
MaxStoreFileSize *

AllowLogSymlinks on

# stdout doesn't work
# unable to open TransferLog '/dev/stdout': No such device or address
# TODO look into why this is the case
TransferLog /dev/stderr
SystemLog   /dev/stderr

# Clears these logs
# mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module
<IfModule mod_delay.c>
  DelayEngine off
</IfModule>

<IfModule mod_sftp.c>
  CreateHome on
  DefaultRoot /home/%u

  SFTPEngine on
  Port 2222
  SFTPAuthMethods     password publickey
  SFTPHostKey /etc/ssh/ssh_host_rsa_key
  SFTPAuthorizedUserKeys file:/etc/sftp/authorized_keys/%u
</IfModule>

<IfModule mod_sql.c>
  TraceLog /var/log/sql.log
  Trace auth:20 sql:20 sql.postgres:20

  AuthOrder mod_sql.c
  SQLLogFile /var/log/sql.log
  SQLBackend postgres
  SQLPasswordEngine on

  SQLAuthTypes bcrypt
  SQLPasswordRounds 10

  SQLAuthenticate users groups
  #SQLConnectInfo sftp@postgres proftp example
  SQLConnectInfo  %{env:FTP_DB_NAME}@%{env:FTP_DB_HOST} %{env:FTP_DB_USER} %{env:FTP_DB_PASS}
  SQLUserInfo     ftp.users userid passwd uid gid homedir shell
  SQLGroupInfo    ftp.groups groupname gid members
  SQLDefaultUID   65533
  SQLDefaultGID   65533

  # Update the ftp.users.last_accessed column on successful login in the userdb
  SQLNamedQuery last_accessed UPDATE "last_accessed = NOW() WHERE userid='%u'" ftp.users
  SQLLog PASS last_accessed

  # Add a row to the ftp.login_history table on successful login in the logdb
  SQLNamedQuery log_session FREEFORM "INSERT INTO ftp.login_history (userid, client_ip, server_ip, protocol, login_date) VALUES ('%u', '%a', '%V', '%{protocol}', NOW())"
  SQLLog PASS log_session IGNORE_ERRORS
</IfModule>
```

**Comment by Castaglia** [comment] 2023-06-22 20:13
Does your ProFTPD installation also include/use the [`mod_ifsession`](http://www.proftpd.org/docs/contrib/mod_ifsession.html) module by any chance?  If so, we may be able to configure a workaround, while I track down the cause of this issue.

**Comment by Castaglia** [comment] 2023-06-22 20:15
Also, just to confirm, this is in the context of SFTP (not FTP) uploads, correct?

**Comment by DanielWozniak94** [comment] 2023-06-22 20:20
I don't have module `mod_ifsession` currently but its not a problem to get it added in.
Thats correct, this is for SFTP.

**Comment by Castaglia** [comment] 2023-06-23 00:21
Once `mod_ifsession` is available, you should be able to use this alternative configuration:
```
<IfUser restricted-user>
  MaxStoreFileSize 10 Mb
</IfUser>
```
I'm hoping I'll have a patch/fix for this issue shortly.

**Comment by Castaglia** [comment] 2023-06-23 00:53
This should now be fixed in `master`.  Thanks!

**Closed by Castaglia** 2023-06-23 00:53 UTC
Labels: bug
