### ISSUE TITLE
RADIUS Message-Authenticator verification failed with ProFTPD mod_radius

### ISSUE THREAD

**Issue by tomglx** [proftpd/proftpd#1840] opened 2024-10-11 09:12 UTC
Hello,

we're using freeradius 3.0.27 with proftpd 1.3.8b and mod_radius.
This freeradius version contains a migitation against the BlastRadius attack.
So the Message Authenticator Attribute is now inserted in any Access Reply Packet.

We've used freeradius 3.0.25 previously without any problem.

mod_radius now rejects the Access-Accept Packets with the following error:
> packet Message-Authenticator verification failed: mismatched MACs

I've debugged this further and discovered some oddities in mod_radius.
In rfc2869 the length of the message authenticator attribute is defined as 18 bytes.
It also says:
 > When the checksum is calculated the signature string should be
 > considered to be sixteen octets of zero

My First question is. Why do you test that the attribute length must be not equal to the expected length of 16 bytes?
If they are equal (what one would expect to be right) an error about incorrect attribute length is raised. Why?
Why won't you test the attribute length to the value of 18 bytes given in the rfc?

The main problem for me is further down the road. The following code excerpt overwrites more in the packet
as it should:
`/* Next, zero out the value so that we can calculate it ourselves. */`
`memset(attrib->data, '\0', attrib_len);`

The attribute length is mostly 18 bytes as it should. So this amount is overwritten in the packet.

The following comparison takes only the interesting amount of bytes into account. This is correct.
`      if (memcmp(replied, digest, expected_len) != 0) {`

But this code fails every time. The reason is, that the hash calculation 
`if (HMAC(md, secret, secret_len, (unsigned char *) pkt,
          ntohs(pkt->length), digest, &digest_len) == NULL) {`
gives a wrong result.

By modifying the memset call to
`memset(attrib->data, '\0', expected_len);`
I'm now getting the right hash calculated. So the comparison works and the Access Accept Packet from
freeradius is considered valid. So I assume that the packet was corrupted previously by overwriting to much.

What is your opinion about this change? Are my assumptions correct?
Should the mod_radius code be corrected?

Best regards, Thomas

**Comment by Castaglia** [comment] 2024-10-11 16:08
This definitely looks like a bug in mod_radius, revealed by the changes in FreeRADIUS.  The change seems OK to me from the description.  I'll reproduce this issue locally, so that I have a way to test for regressions, and then fix this in mod_radius.

Thanks for reporting this issue!

**Comment by Castaglia** [comment] 2024-10-26 19:08
This has now been fixed in master, and backported to the 1.3.8 branch.  Thanks!

**Closed by Castaglia** 2024-10-26 19:08 UTC
Labels: bug, backport
