### ISSUE TITLE
Add crosscompiling support for ./configure.in

### ISSUE THREAD

**Issue by icegood** [proftpd/proftpd#1768] opened 2024-01-06 19:02 UTC
For now during configuration of the module for other platform we will obtain:

```
checking whether listen supports negative backlog... 
configure: error: in /home/ice/external/openwrt_build/under_env/openwrt_22_series_for_dlink620/build_dir/target-mipsel_24kc_musl/proftpd-28e60b76':
configure: error: cannot run test program while cross compiling

```

the issue could be fixed if all of macroses AC_TRY_RUN will be feed with 
`
AC_MSG_RESULT(cross-compiling);
`
and some random guesses under cross compilation

**Comment by Castaglia** [comment] 2024-01-06 19:15
Can you explain your use cases/needs, for why/when you'd like such cross-compiling support?

**Comment by Castaglia** [comment] 2024-12-11 14:16
Closing this as a duplicate of Issue #1857.

**Closed by Castaglia** 2024-12-11 14:16 UTC
Labels: enhancement
