### ISSUE TITLE
When SFTP client requests a lower version of SFTP protocol than allowed by SFTPClientMatch sftpProtocolVersion, mod_sftp does not respect the client

### ISSUE THREAD

**Issue by martinprikryl** [proftpd/proftpd#1200] opened 2021-03-19 12:43 UTC
### What I Did
`proftpd.conf`:
```
SFTPClientMatch ".*WinSCP.*" sftpProtocolVersion 6
```
Connect with WinSCP configured to ask for SFTP version 3 (or any lower than 6).

### What I Expected/Wanted

`draft-ietf-secsh-filexfer-13` says in [*5.2.  Server Initialization*](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-5.2):

>    'version' is the lower of the protocol version supported by the server and the version number received from the client.

Even the SFTPv3 specification `draft-ietf-secsh-filexfer-02` says in [4. Protocol Initialization](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-03#section-4):

> The server responds with a SSH_FXP_VERSION packet, supplying the   lowest of its own and the client's version number.

So assume the only right solution is to disconnect the client.

### ProFTPD Version and Configuration

ProFTPD built from the master (currently 5fa01bc3).

Relevant code in `fxp_handle_init`:  
https://github.com/proftpd/proftpd/blob/v1.3.7a/contrib/mod_sftp/fxp.c#L7722-L7729

Thanks.

**Comment by Castaglia** [comment] 2021-03-21 15:30
Could you configure trace logging for `mod_sftp`, using:
```
TraceLog /path/to/sftp-trace.log
Trace ssh2:30 sftp:30
```
And provide the generated logs from the above WinSCP connection?  This will help me see the exact SSH/SFTP packets written to the wire, to make sure I will handle them properly.  Thanks!

**Comment by Castaglia** [comment] 2021-03-21 16:05
Actually, I don't need the requested trace logging; I believe I've reproduced this locally:
```
<sftp:6>: received INIT (1) SFTP request (channel ID 0)
<sftp:7>: received request: INIT 3
mod_sftp/1.0.1[44752]: client requested SFTP protocol version 3, which is less than SFTPClientMatch min SFTP protocol version 6, using protocol version 6
mod_sftp/1.0.1[44752]: using SFTP protocol version 6 for this session (channel ID 0)
<sftp:8>: sending response: VERSION 6
```
The above is what is logged when NLS support (via the `--enable-nls` configure option) is enabled.

However, when NLS support is *not* enabled, the logs look like this:
```
<sftp:6>: received INIT (1) SFTP request (channel ID 0)
<sftp:7>: received request: INIT 3
mod_sftp/1.0.1[54017]: client requested SFTP protocol version 3, which is less than SFTPClientMatch min SFTP protocol version 6, using protocol version 6
mod_sftp/1.0.1[54017]: client requested SFTP protocol version 6, but we can only support protocol version 3 due to lack of UTF8 support (requires --enable-nls)
mod_sftp/1.0.1[54017]: using SFTP protocol version 3 for this session (channel ID 0)
<sftp:8>: sending response: VERSION 3
```

**Comment by Castaglia** [comment] 2021-03-22 18:24
As I see it, there are two possible actions: the server rejects/closes the connection (due to inability to support the requested protocol version), or the client rejects/closes the connection (due to the inability of the server to support the requested protocol version).

If the server closes the connection (e.g. via TCP close), it does not have a good way to report the reasons _why_ it's abruptly terminating the connection.  We could try to use the `PROTOCOL_VERSION_NOT_SUPPORTED` SSH2 disconnect reason code, but IMHO that applies to the SSH protocol version, not the SFTP protocol version.  And thus the client would see its connection abruptly terminated, with no context -- and that would not be a great end user experience.

Alternatively, one might argue that the client can read the server's `VERSION` response, see that the server's supported protocol version does not align/support the protocol version requested by the client, and thus the client can then _a)_ show the user why the client is closing the connection, and _b)_ close the connection itself.

I favor the latter approach, where the client decides to terminate the connection, because of the better user experience.

**Comment by martinprikryl** [comment] 2021-03-23 08:51
I understand all that. But the thing is that your current implementation violates the specification.

Some clients do not even check for this scenario (getting a higher version than asked for). So they assume they got the version they have asked for.

- OpenSSH `sftp` does not check. It only checks, if it gets a lower version. If it gets a higher one, it still behaves like the version is v3. As it does `SSH2_FXP_REALPATH` at the very beginning, which has additional field in v6, ProFTPD bails on that. But for v4 and v5, it will get past that step and may cause more chaos later (I didn't test this).
- WinSCP does not check either. But as it (currently) supports all versions that proftpd does, no problem can occur.

**Comment by martinprikryl** [comment] 2021-03-23 12:51
> * As it does `SSH_FXP_REALPATH` at the very beginning, which has additional field in v6, ProFTPD bails on that.
That was not correct, as the new field is additional. Rather OpenSSH fails on decoding the v6 `SSH_FXP_NAME` returned by ProFTPD.

**Comment by Castaglia** [comment] 2021-03-24 01:03
In this particular regard, the specs don't explicitly say that servers should (or should not) disconnect clients for incompatible requested protocol versions, so...I feel we're in undefined behavior territory.

As I said before, while I see the functional benefit (preserving/using the actually requested SFTP protocol version), I don't like the fact that, when these situations happen, the client would be disconnected abruptly, with no indication of why.  That might cause more reports of problems by users than the current situation.

**Comment by martinprikryl** [comment] 2021-03-24 07:15
I understand that closing the connection abruptly is not a nice thing to do. But imo, it's the only solution available that adheres to the specification. Thanks for the change.

**Comment by Castaglia** [comment] 2021-03-24 15:10
Will you also be changing WinSCP, so that it checks the `VERSION` response from other SFTP servers, to also adhere (as best possible) to the specification?  Not all servers will abruptly disconnect in such situations; the responsibility lies equally with both server and client.

**Comment by martinprikryl** [comment] 2021-03-24 15:47
As I wrote above, WinSCP already checks that the version, it gets from the server, is not higher, than the version it supports (v6). It also logs the version negotiated. The next version will additionally log a warning, when the version, it gets from the server, is higher than, what it asked for (what the user configured WinSCP to use).

**Comment by Castaglia** [comment] 2021-03-27 15:57
Fixed in master.

**Closed by Castaglia** 2021-03-27 15:57 UTC
Labels: bug
