### ISSUE TITLE
Update integration tests

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#362] opened 2016-12-09 14:14 UTC
### What I Did

Running integration tests in /tests

### What I Expected/Wanted

The current integration tests rely on a very old perl package (10 plus years). While the right solution at the time, it has grown stale. The maintainers of the project have stated  that it the project is in essence "dead".

The desired outcome would be an updated integration test in perl or something else using current, well supported packages.

### ProFTPD Version and Configuration

Latest compiled from source

**Comment by Castaglia** [comment] 2016-12-16 15:16
This is a duplicate of [Bug#4064](http://bugs.proftpd.org/show_bug.cgi?id=4064); I'll close this as such.

**Closed by Castaglia** 2016-12-16 15:16 UTC
