### ISSUE TITLE
Unsupported protocol sequence

### ISSUE THREAD

**Issue by mflage** [proftpd/proftpd#782] opened 2019-02-11 11:11 UTC
Hi!

We've been using proftpd and its mod_sftp for a while now and it seems to be working just fine. But more recently we've gotten a new client connecting towards us using the QtCreator sftp library and they are having issues connecting towards us.

> 2019-02-06 20:18:50,271 mod_sftp/0.9.9[4396]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
> 2019-02-06 20:18:50,271 mod_sftp/0.9.9[4396]: received client version 'SSH-2.0-QtCreator'
> 2019-02-06 20:18:50,271 mod_sftp/0.9.9[4396]: handling connection from SSH2 client 'QtCreator'
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session key exchange: diffie-hellman-group1-sha1
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session server hostkey: ssh-rsa
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session client-to-server encryption: aes128-cbc
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session server-to-client encryption: aes128-cbc
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session client-to-server MAC: hmac-sha1
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session server-to-client MAC: hmac-sha1
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session client-to-server compression: none
> 2019-02-06 20:18:50,454 mod_sftp/0.9.9[4396]:  + Session server-to-client compression: none
> 2019-02-06 20:18:50,828 mod_sftp/0.9.9[4396]: sending userauth success
> 2019-02-06 20:18:50,828 mod_sftp/0.9.9[4396]: user 'XXXXX' authenticated via 'password' method
> 2019-02-06 20:18:51,193 mod_sftp/0.9.9[4396]: 'subsystem' channel request for 'sftp' subsystem
> 2019-02-06 20:18:51,375 mod_sftp/0.9.9[4396]: using SFTP protocol version 3 for this session (channel ID 0)
> 2019-02-06 20:19:01,012 mod_sftp/0.9.9[4396]: unhandled (unknown) (-128) message, disconnecting
> 2019-02-06 20:19:01,012 mod_sftp/0.9.9[4396]: disconnecting (Unsupported protocol sequence)

I've read through the code for mod_sftp and found this to be in the packet.c source file and the following code [1]:

```
    default:
      pr_event_generate("ssh2.invalid-packet", pkt);

      (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
        "unhandled %s (%d) message, disconnecting",
        sftp_ssh2_packet_get_mesg_type_desc(mesg_type), mesg_type);
      SFTP_DISCONNECT_CONN(SFTP_SSH2_DISCONNECT_BY_APPLICATION,
        "Unsupported protocol sequence");
```
So either the client is sending an unknown message that's not handled correctly or there are some problems when interpreting the messages coming from the client...?

I'm using the default proftpd from Ubuntu 18.04 LTS, output from proftpd -V below:

> Compile-time Settings:
>   Version: 1.3.5e (maint)
>   Platform: LINUX [Linux 4.15.0-45-generic x86_64]
>   Built: Mon Feb 5 2018 23:27:47 

--
Marius

[1] https://github.com/proftpd/proftpd/blob/8d593a60c7e66c637396739dc37d46d08694f7c6/contrib/mod_sftp/packet.c#L1647

**Comment by Castaglia** [comment] 2019-04-22 17:09
This log message:
```
2019-02-06 20:19:01,012 mod_sftp/0.9.9[4396]: unhandled (unknown) (-128) message, disconnecting
```
indicates the root of the issue, I think.  Every SSH2 message, and every SFTP packet, have a _type_, a numeric ID that identifies that message/package.  The above log message indicates that the client in question is sending a message/packet an unknown type -- usually this indicates a bug of some sort in the client.

**Comment by mflage** [comment] 2019-04-22 18:55
> This log message:
> 
> ```
> 2019-02-06 20:19:01,012 mod_sftp/0.9.9[4396]: unhandled (unknown) (-128) message, disconnecting
> ```
> indicates the root of the issue, I think. Every SSH2 message, and every SFTP packet, have a _type_, a numeric ID that identifies that message/package. The above log message indicates that the client in question is sending a message/packet an unknown type -- usually this indicates a bug of some sort in the client.

Ah, thanks. That was also what I thought myself. Is there a way I can confirm this? I guess there is no way of debugging the connection itself?

**Comment by Castaglia** [comment] 2019-04-23 00:28
Interesting.  I am looking through the `qt-creator` source code on GitHub; it looks to be using the OpenSSH command-line `ssh` (see [here](https://github.com/qt-creator/qt-creator/blob/46c287fee5cea9a4f83c554e2162301a8a70ae5d/src/libs/ssh/sshconnection.cpp#L127)) and `sftp` (see [here](https://github.com/qt-creator/qt-creator/blob/46c287fee5cea9a4f83c554e2162301a8a70ae5d/src/libs/ssh/sftpsession.cpp#L102)) utilities.  And if that is the case -- and we know that OpenSSH works with `mod_sftp` -- then why would this particular error be happening?  Hmm.  I'll keep looking through this source.

**Comment by Castaglia** [comment] 2019-04-23 00:44
Unless perhaps your new client is using an older QtCreator library, before [this commit](https://github.com/qt-creator/qt-creator/commit/d7178b88c4b2572fb83b28f8178940766216deed)?

**Comment by mflage** [comment] 2019-04-24 18:02
Hi!

I have talked with the customer. It turns out it's this library that's
being used: https://github.com/lvklabs/QSsh

--
Marius

**Comment by jschmitz913** [comment] 2019-05-20 15:03
Is there any update on this? We have a customer who just updated OpenSSH to 7.5.102.1600 and are now getting this error when trying to connect to us. All I'm seeing in the logs is:

2019-05-20 09:35:01,227 [35157] <ssh2:10>: auth requested for user 'removed', service 'ssh-connection', using method 'none'
2019-05-20 09:35:01,242 [35157] <ssh2:10>: auth requested for user 'removed', service 'ssh-connection', using method 'publickey'

That's it - nothing in the SFTP logs at all. We're running ProFTPD 1.3.6 on RHEL 7.6.

**Comment by Castaglia** [comment] 2019-05-20 15:29
@jschmitz913 that behavior sounds similar to -- but not the same -- as the QtCreator client described in this ticket.  Would you mind opening a separate ticket for that OpenSSH client?  I suspect the root causes will be different for these different SSH clients.

**Comment by hbarrett** [comment] 2020-02-26 19:17
We get this message with the latest windows FIlezilla  and WinSCP clients as well.

**Comment by Castaglia** [comment] 2020-02-26 19:18
@hbarrett I think you may be seeing this, for FileZilla/WinSCP, due to [Bug #4385](http://bugs.proftpd.org/show_bug.cgi?id=4385).

**Comment by hbarrett** [comment] 2020-02-26 19:24
@Castaglia Yes, I think you are correct. Thanks.

**Comment by Castaglia** [comment] 2020-07-26 15:38
If there's nothing more to add to this report, I'd like to close it.

**Comment by Castaglia** [comment] 2020-11-08 18:54
Closing this ticket, after no additional feedback/information after several months.

**Closed by Castaglia** 2020-11-08 18:54 UTC
Labels: question, waiting for feedback
