### ISSUE TITLE
"make install" target should not trigger compilation for `--with-shared=mod_auth_otp`

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1451] opened 2022-05-11 06:14 UTC
### What I Did

This a reopening of  #548. I just noticed that the issue is not fully solved, there are still compile steps executed after successful build.

### What I Expected/Wanted

I'd expect that after the successful build no calls to gcc are executed any more.

### ProFTPD Version and Configuration

I tested using proftp 1.3.8rc3, my build log [is attached](https://github.com/proftpd/proftpd/files/8667185/proftpd-dfsg_1.3.8rc3-1_amd64-2022-05-09T21.3A47.3A03Z.build.zip). You should be able to see all configure options we use.

In line 3015, the debhelper-build-stamp file is generated, i.e. I'd expect that the build is done. Nevertheless we see in line 3313 that gcc is called to build `auth-otp`. I'd expect that this step is moved to the build stage.

### Impact

I noticed that proftp currently fails in the Debian Salsa CI exactly at [this step](https://salsa.debian.org/debian-proftpd-team/proftpd/-/jobs/2733927#L2251). We suspect that the build stage is done by a different user than the install stage, hence writing new files into the build tree fails.

Many thanks for looking into this!

**Comment by Castaglia** [comment] 2022-05-11 14:50
Did you notice this only for `auto-otp`?  That is, is the scope of this ticket specific to use of optional, opt-in contrib modules, or does it happen when only the core code, no contrib modules, are used?

**Comment by hpreusse** [comment] 2022-05-11 21:33
Well, the compile step of `mod_auth_otp` is currently the only place, where I see build actions during install steps. So, this should be the only issue of this kind. I could try w/ `mod_auth_otp` disabled if that helps you in any way, but I don't expcet trouble then.

**Comment by Castaglia** [comment] 2022-05-12 00:20
No, that's OK, I should be able to reproduce this behavior locally.  Just wanting to _a)_ see if you'd seen a regression of Issue #548 when compiling only the core code, or _b)_ if you'd seen this behavior from any other modules than `mod_auth_otp`.

**Comment by Castaglia** [comment] 2022-05-12 00:28
I suspect this behavior occurs only when building `mod_auth_otp` as a shared module; when built as a static module, the `auth-otp` utility should be built on just `make`, per [this Makefile instruction](https://github.com/proftpd/proftpd/blob/master/contrib/mod_auth_otp/Makefile.in#L39).  I'm confirming this now.

**Comment by Castaglia** [comment] 2022-05-12 00:42
@hpreusse https://github.com/proftpd/proftpd/pull/1452 looks to address this for me locally; care to verify that it fixes the issue for you as well?

**Comment by hpreusse** [comment] 2022-05-12 21:40
> @hpreusse #1452 looks to address this for me locally; care to verify that it fixes the issue for you as well?
> 
I can confirm that there is no call to gcc after build has finished: the binary in question is built in build stage. Many thanks!

**Comment by Castaglia** [comment] 2022-05-12 21:52
Excellent, thanks for confirming @hpreusse .  Will you need this backported to the 1.3.7 branch?

**Comment by Castaglia** [comment] 2022-05-13 00:26
> Excellent, thanks for confirming @hpreusse . Will you need this backported to the 1.3.7 branch?

Well, since I didn't backport the fix for Issue #548 to the 1.3.7 branch, I won't back port this one, either.

Fix merged to master.  Thanks!

**Closed by Castaglia** 2022-05-13 00:26 UTC
Labels: build
