### ISSUE TITLE
mod_sftp_sql logs "header value too long" due to unexpected key header text

### ISSUE THREAD

**Issue by maltris** [proftpd/proftpd#1529] opened 2022-09-23 10:49 UTC
### What I Did

Setup proftpd with mod_sftp_sql. Sometimes the log gets spammed with thousands

```
mod_sftp_sql/0.4[31282]: header value too long (4294967295) in retrieved SQL data
```

The longest values I have in the (Percona XtraDB-based) DB are 800 bytes (ssh user keys). I do not fully understand where a value of 4294967295 (32 bit int limit??) bytes should come from.

The configuration below is a little messy, it serves to serve sftp as well as ftp and ftps with all auth information coming from the DB.

Can you please guide me through debugging this and finding the cause for it?

### What I Expected/Wanted

Clean log, all users able to login

### ProFTPD Version and Configuration

Please help us reproduce the problem/issue you are encountering.  To do this,
we need to know which version of ProFTPD you are using, how it was built,
_etc_.  The following command is an easy way to get all of this information:

<details>
  <summary>proftpd -V</summary>

```
/ # proftpd -V
Compile-time Settings:
  Version: 1.3.7c (maint)
  Platform: LINUX [Linux 5.4.0-120-generic x86_64]
  Built: Thu Dec 16 2021 15:43:14 UTC
  Built With:
    configure  '--enable-ctrls' '--enable-openssl' '--enable-quotatab' '--with-modules=mod_tls:mod_quotatab:mod_sql:mod_sql_passwd:mod_quotatab_sql:mod_quotatab_file:mod_ifsession:mod_ctrls_admin:mod_auth_otp:mod_sql_sqlite:mod_sql_mysql:mod_ban:mod_readme:mod_sftp:mod_sftp_sql:mod_proxy_protocol:mod_ident' '--enable-nls'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic  -L/usr/lib/
  LIBS:  -lssl -lcrypto -lm -lmysqlclient -lz  -lsqlite3  -lssl  -lcrypto -lsupp 

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    + OpenSSL support (OpenSSL 1.1.1l  24 Aug 2021)
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

```

</details>

In addition, we need to see **all** of the ProFTPD configuration files you are
using (**minus** any sensitive information like passwords, of course).  Armed
with the version and configuration data, then, we can set up ProFTPD locally
using the same configuration, and see what happens.

<details>
  <summary>Configuration</summary>

```
<global>
RootLogin off
RequireValidShell off
AllowOverwrite on
WtmpLog off
TransferLog /var/log/xfer.log
DefaultRoot ~

IdentLookups                    off
DeferWelcome                    off
MultilineRFC2228                on
ShowSymlinks                    on

TimeoutNoTransfer               6000
TimeoutStalled                  6000
TimeoutIdle                     12000

QuotaEngine on
QuotaDirectoryTally on
QuotaDisplayUnits Mb
QuotaShowQuotas on
QuotaOptions ScanOnLogin

SQLNamedQuery get-quota-limit SELECT "name, quota_type, per_session, limit_type, bytes_in_avail, bytes_out_avail, bytes_xfer_avail, files_in_avail, files_out_avail, files_xfer_avail FROM ftpquotalimits WHERE name = '%{0}' AND quota_type = '%{1}'"
SQLNamedQuery get-quota-tally SELECT "name, quota_type, bytes_in_used, bytes_out_used, bytes_xfer_used, files_in_used, files_out_used, files_xfer_used FROM ftpquotatallies WHERE name = '%{0}' AND quota_type = '%{1}'"
SQLNamedQuery update-quota-tally UPDATE "bytes_in_used = bytes_in_used + %{0}, bytes_out_used = bytes_out_used + %{1}, bytes_xfer_used = bytes_xfer_used + %{2}, files_in_used = files_in_used + %{3}, files_out_used = files_out_used + %{4}, files_xfer_used = files_xfer_used + %{5} WHERE name = '%{6}' AND quota_type = '%{7}'" ftpquotatallies
SQLNamedQuery insert-quota-tally INSERT "%{0}, %{1}, %{2}, %{3}, %{4}, %{5}, %{6}, %{7}" ftpquotatallies

QuotaLimitTable sql:/get-quota-limit
QuotaTallyTable sql:/get-quota-tally/update-quota-tally/insert-quota-tally

SQLBackend              mysql
SQLAuthTypes            Crypt
SQLAuthenticate         users groups

SQLConnectInfo  REDACTED ssl-ca:/path/to/cacert.pem

SQLGroupInfo    ftpgroup groupname gid members
SQLMinID        500
CreateHome on

SQLLog PASS updatecount
SQLNamedQuery updatecount UPDATE "count=count+1, accessed=now() WHERE userid='%u'" ftpuser

SQLLog  STOR,DELE modified
SQLNamedQuery modified UPDATE "modified=now() WHERE userid='%u'" ftpuser

SQLNamedQuery get-user-authorized-keys SELECT "user_key FROM sftpuserkeys WHERE user='%U'"

SQLNamedQuery get-host-authorized-keys SELECT "host_key FROM sftphostkeys WHERE host='%{0}'"

    <Directory /proc>
        <Limit ALL>
            DenyAll
        </Limit>
    </Directory>

    <IfModule mod_proxy_protocol.c>
        ProxyProtocolEngine on
        ProxyProtocolVersion haproxyV2
        AllowForeignAddress on
    </IfModule>

</global>

<IfModule mod_sftp.c>
    <VirtualHost 0.0.0.0>
        Port 22
        SFTPOptions     IgnoreSFTPUploadPerms
        SFTPEngine      on
        SFTPCompression delayed

        SFTPHostKey /etc/ssh/ssh_host_rsa_key
        SFTPHostKey /etc/ssh/ssh_host_ecdsa_key

        SQLUserInfo     ftpusersftp userid passwd uid gid homedir shell

        <IfModule mod_sftp_sql.c>
             SFTPAuthorizedUserKeys sql:/get-user-authorized-keys
             SFTPAuthorizedHostKeys sql:/get-host-authorized-keys
        </IfModule>

	SFTPLog /var/log/sftp.log
    </VirtualHost>
</IfModule>

<IfModule mod_sql_passwd.c>
    <VirtualHost 0.0.0.0>
        <IfModule mod_tls.c>
            TLSEngine on
            TLSRequired off
            TLSRSACertificateFile REDACTED.pem
            TLSRSACertificateKeyFile REDACTED.key
            TLSOptions                 NoCertRequest NoSessionReuseRequired
        </IfModule>

        Port 21
        DefaultServer on

        PassivePorts 10000 10250
        MasqueradeAddress REDACTED

        SQLPasswordEngine on

        SQLUserInfo     ftpuser userid passwd uid gid homedir shell
    </VirtualHost>
</IfModule>

Port 0

UseIPv6                         off
UseReverseDNS                   off

ServerName                      "FTP"
ServerType                      standalone

SystemLog /var/log/proftpd.log
SyslogLevel info
```

</details>

**Comment by Castaglia** [comment] 2022-09-25 18:05
Do these "header too long" log messages appear consistently (for _e.g._ the same users, clients, or SSH keys), or does it appear to be random, where the same user/client/key sometimes encounters these log messages, and sometimes not?

**Comment by maltris** [comment] 2022-09-26 09:36
Thats the weird part:

The message is logged a thousand times in a very short timeframe. I cannot correlate the message with any users, because of the content of the message (see above). Is there any way to add the useraccount to this logmessage?

**Comment by Castaglia** [comment] 2022-10-01 18:35
@maltris I've pushed a change to `master`, to add logging of the username to the `mod_sftp_sql` message in question, if you'd like to try it out, see what more details we can find?

**Comment by Castaglia** [comment] 2023-02-18 21:42
As there's been no further commentary/additions to this ticket, I'm going to close it.

**Comment by maltris** [comment] 2024-04-17 10:49
I have fresh information. Using the patch, I was able to find an anomaly in the database contents for a specific user.

While a normal user had the key in the MySQL db like this:

```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "Some comment is here"
AAAAB3NzaC1yc2EAAAADAQABAAABgQCqET7/fVzjpfSgsHEFVmBRFSzPaCWUJISiX6ZD+U
vZl8FeQMIR2z6K1F+viaZrb0P4piAkEgdp6SMH0k4pbrj3vQArwuTB7043gazhB7oyhR1Q
/MZOc2zqO74gI6jpdASvSqR14uQOA70Fqd1d/6NjUmbQoCMXYobHEUV0T6QbKgTgecZFbA
VstDGvkxjDscbYjiO8ALCaCwwP+UB/jHn2gzqx458u8U1lnTc7/lBOY0qHArzKWKXTjZkn
d+PISOez+lc0eyKFXA3PA1iDHdlY2MKYGkg/U0UwCJaqHvfeVAsJFjfHdn8EzXb247JRxR
SGXQYrqvogsClfRjVs/XyzeIO4c4iwLmwJcZkaxn0Fexlr5T+0BJgpRXhlbH8t0Gbl6g4k
FcBTTwKHrf2Ii4rbuua0R0v9Ok6Yyf9yoL0qQy/JneWBDM6g/WBvdYpQwggaif9zWNn44l
Frf0CNU3YHRxRhjEI6Z/6ja6nk30cJVkjUkjE3qjzIKnNkqnKnPSM=
---- END SSH2 PUBLIC KEY ----
```

This particular user had:

```
---- BEGIN SSH2 PUBLIC KEY ----
Comment:
AAAAB3NzaC1yc2EAAAADAQABAAABgQCqET7/fVzjpfSgsHEFVmBRFSzPaCWUJISiX6ZD+U
vZl8FeQMIR2z6K1F+viaZrb0P4piAkEgdp6SMH0k4pbrj3vQArwuTB7043gazhB7oyhR1Q
/MZOc2zqO74gI6jpdASvSqR14uQOA70Fqd1d/6NjUmbQoCMXYobHEUV0T6QbKgTgecZFbA
VstDGvkxjDscbYjiO8ALCaCwwP+UB/jHn2gzqx458u8U1lnTc7/lBOY0qHArzKWKXTjZkn
d+PISOez+lc0eyKFXA3PA1iDHdlY2MKYGkg/U0UwCJaqHvfeVAsJFjfHdn8EzXb247JRxR
SGXQYrqvogsClfRjVs/XyzeIO4c4iwLmwJcZkaxn0Fexlr5T+0BJgpRXhlbH8t0Gbl6g4k
FcBTTwKHrf2Ii4rbuua0R0v9Ok6Yyf9yoL0qQy/JneWBDM6g/WBvdYpQwggaif9zWNn44l
Frf0CNU3YHRxRhjEI6Z/6ja6nk30cJVkjUkjE3qjzIKnNkqnKnPSM=
---- END SSH2 PUBLIC KEY ----
```

Somehow this empty "Comment:" triggered the "header value too long (4294967295) in retrieved SQL data" even without the header value really being too long. I suppose the error message was a general message emitted when a parsing error was caught?

Adding the patch with the username aided finding the anomaly. Adding a comment to the key solved the problem.

**Comment by Castaglia** [comment] 2024-04-18 15:37
@maltris Thanks for the follow-up!  Once I have some free time, I'll use the info to hopefully reproduce (and _properly fix_) this handling of an empty/missing `Comment`.

**Comment by Castaglia** [comment] 2024-04-20 16:38
I've reproduced the issue locally, and can confirm that the issue still exists in the latest code in `master`, caused by a line of text like `Comment:` (note the lack of space character after the `:` character).

**Comment by Castaglia** [comment] 2024-04-20 17:03
@maltris I know you've corrected the offending entries in your database, but you might be interested in testing/seeing the fix for this: https://github.com/proftpd/proftpd/pull/1796

Thanks!

**Comment by Castaglia** [comment] 2024-04-20 18:00
This should now be fixed (properly!) in master, and backported to the 1.3.8 branch.  Thanks!

**Closed by Castaglia** 2024-04-20 18:00 UTC
Labels: bug, backport
