### ISSUE TITLE
Updating to 1.3.5d-1.el7 on Centos 7 via YUM causes error (signal 11)

### ISSUE THREAD

**Issue by newmediaone** [proftpd/proftpd#408] opened 2017-02-05 03:15 UTC
### What I Did
I'm running Centos7 on Google Cloud.  Yum signaled an update from:
proftpd-1.3.5b
To 1.3.5d
(Yum shows:
The available updates are:

    proftpd.x86_64                         1.3.5d-1.el7                         epel)

I use proftpd for SFTP by adding this line to my `sshd_config`:

    Subsystem       sftp    /usr/libexec/openssh/sftp-server

*and* these lines to the end of `/etc/proftpd.conf`:

    LoadModule mod_sftp.c
    <IfModule mod_sftp.c>
        # Configure the server to listen on the normal SSH2 port, port 22
        Port 2222
        #PidFile /run/prosftpd/prosftpd.pid
        SFTPEngine on
        #SFTPLog /var/log/prosftpd/sftp.log
        #ScoreboardFile /run/prosftpd/prosftpd.scoreboard
        # Configure both the RSA and DSA host keys, using the same host key
        # files that OpenSSH uses.
        SFTPHostKey /etc/prosftpd/ssh_host_rsa_key
        #SFTPHostKey /etc/ssh/ssh_host_dsa_key
        # Enable compression
        SFTPCompression delayed
        # Allow the same number of authentication attempts as OpenSSH.
        #
        # It is recommended that you explicitly configure MaxLoginAttempts
        # for your SSH2/SFTP instance to be higher than the normal
        # MaxLoginAttempts value for FTP, as there are more ways to authenticate
        # using SSH2.
        MaxLoginAttempts 6
        SFTPClientMatch .*ClientSftp sftpProtocolVersion 3
    </IfModule>

After updating to 1.3.5d via YUM if any attempt to SFTP in failed with an login error, but checking the logs, it looks like it's crashing with signal 11.

Here's what the logs show on SFTP connection attempt (IP address part of logs removed):

    SSH2 session opened.
    ProFTPD terminating (signal 11)
    SSH2 session closed.

*After* reverting back, the logs show (IP address part of logs removed):

    SSH2 session opened.
    USER REALFTPUSENAMEHERE: Login successful

It appeared that _some_ SFTP clients (Coda on Mac) _still_ worked, but others (Yummy and Transmit on Mac) failed with signal 11.

I thought perhaps it was a issue with a certain encryption typeS, but after creating a valid DSA key and adding it to the configuration, I saw no difference.

Ultimately, after trying everything I could think of, I had to revert back by doing a local install using
proftpd-1.3.5b-2.el7.x86_64.rpm

After reverting back, everything worked as before.

### What I Expected/Wanted

I was surprised the update caused SFTP to fail.  I use YUM for EVERYTHING on my servers, and have had no issues thus far with updating anything with YUM.

### ProFTPD Version and Configuration

    proftpd -V
    Compile-time Settings:
      Version: 1.3.5b (maint)
      Platform: LINUX [Linux 3.10.0-514.6.1.el7.x86_64 x86_64]
      Built: Wed Jun 1 2016 09:34:39 UTC
      Built With:
        configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-shadow' '--enable-tests' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic'

      CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall
      LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64/mysql -L/usr/lib64/mysql -L/usr/lib64
      LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lssl -lcrypto  -lpam -lsupp -lcrypt -ldl 

      Files:
        Configuration File:
          /etc/proftpd.conf
        Pid File:
          /run/proftpd/proftpd.pid
        Scoreboard File:
          /run/proftpd/proftpd.scoreboard
        Header Directory:
          /usr/include/proftpd
         Shared Module Directory:
          /usr/libexec/proftpd

      Features:
        - Autoshadow support
        + Controls support
        + curses support
        - Developer support
        + DSO support
        + IPv6 support
        + Largefile support
        - Lastlog support
        + Memcache support
        + ncursesw support
        + NLS support
        + OpenSSL support (FIPS enabled)
        + PCRE support
        + POSIX ACL support
        + Shadow file support
        + Sendfile support
        + Trace support

      Tunable Options:
        PR_TUNABLE_BUFFER_SIZE = 1024
        PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
        PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
        PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
        PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
        PR_TUNABLE_HASH_TABLE_SIZE = 40
        PR_TUNABLE_NEW_POOL_SIZE = 512
        PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
        PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
        PR_TUNABLE_SELECT_TIMEOUT = 30
        PR_TUNABLE_TIMEOUTIDENT = 10
        PR_TUNABLE_TIMEOUTIDLE = 600
        PR_TUNABLE_TIMEOUTLINGER = 30
        PR_TUNABLE_TIMEOUTLOGIN = 300
        PR_TUNABLE_TIMEOUTNOXFER = 300
        PR_TUNABLE_TIMEOUTSTALLED = 3600
        PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

I use proftpd for SFTP by adding this line to the end of my `sshd_config`:

    Subsystem       sftp    /usr/libexec/openssh/sftp-server

`/etc/proftpd.conf` is attached.

Thanks in advance for all the help and providing this software.

Peter

[proftpd.conf.txt](https://github.com/proftpd/proftpd/files/752714/proftpd.conf.txt)

**Comment by Castaglia** [comment] 2017-02-05 06:06
One quick note: adding this to your `sshd_config`:

   Subsystem       sftp    /usr/libexec/openssh/sftp-server 

doesn't _actually_ make OpenSSH use ProFTPD for SFTP support; it simply enables OpenSSH's builtin SFTP server.  ProFTPD's `mod_sftp` does not currently support being used as an OpenSSH subsystem; see [Bug#4225](http://bugs.proftpd.org/show_bug.cgi?id=4225).

On your Centos 7 system, what does `openssl version -a` show?

Last, could you add the following to the top of your `<IfModule mod_sftp.c>` section of your `proftpd.conf`, restart proftpd, and then try to log in with one of the clients which fails (and which succeed):

    TraceLog /var/log/prosftpd/sftp.log
    Trace ssh2:20 sftp:20

and attach the generated `sftp.log` file?  That will provide much more detailed logging about what the clients are sending, that might be tickling the "signal 11" behavior.  Thanks!

**Comment by newmediaone** [comment] 2017-02-05 20:17
Thanks for such a quick reply!

Here is the output of openssl version -a:
------------------------------------
openssl version -a
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Sun Nov  6 03:45:24 UTC 2016
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic 
------------------------------------
The log on the OLDER version, which IS working is attached. 
If this doesn't show any issues, I'll update to the current version to get the log on failures.

Thanks again!

Peter 
[SFTPLOG.txt](https://github.com/proftpd/proftpd/files/753258/SFTPLOG.txt)

**Comment by Castaglia** [comment] 2017-02-05 20:59
Ah-hah!  That did help.  It appears that the "signal 11" behavior is tickled/caused by something that OpenSSH 7.3 is doing; using that version of OpenSSH `sftp(1)`, I can cause the "signal 11" behavior.  Digging into the cause now.

**Comment by Castaglia** [comment] 2017-02-05 21:30
I've found the issue, and will have a PR shortly.  I've also opened a bug report about this in the project's main Bugzilla instance; see [Bug#4287](http://bugs.proftpd.org/show_bug.cgi?id=4287).  That is so I can inform other package maintainers of the issue, and the patch, so that they can release fixed `.deb` and `.rpm` files as needed.

**Comment by Castaglia** [comment] 2017-02-05 21:48
Fixed in the 1.3.5 branch.  Thanks!

**Closed by Castaglia** 2017-02-05 21:48 UTC
Labels: bug

**Comment by Castaglia** [comment] 2017-02-05 22:55
As a workaround, for your current 1.3.5d `yum` install, you can configure `mod_sftp` such that it doesn't offer the problematic digest algorithm, using:

    SFTPCiphers hmac-sha1 hmac-md5 hmac-ripemd160

See [`SFTPCiphers`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPDigests).

**Comment by newmediaone** [comment] 2017-02-06 04:54
THANK YOU SO MUCH!  Your response was amazing!

What worked for me as a workaround was slightly different than what you suggested.  This is what worked for me. (SFTPDigests instead of SFTPCiphers).
--------------------
SFTPDigests hmac-md5 hmac-sha1 hmac-sha2-256 hmac-sha2-512 hmac-ripemd160 hmac-sha1-96
--------------------

Thanks again!

Peter

**Comment by Castaglia** [comment] 2017-02-06 06:42
Argh; sorry about that -- I _did_ mean `SFTPDigests`, not `SFTPCiphers` (and have updated my comment, for future readers).
