### ISSUE TITLE
TLSv1.3 handshake fails due to missing session ticket key on some systems

### ISSUE THREAD

**Issue by freultwah** [proftpd/proftpd#1014] opened 2020-05-13 10:24 UTC
I am running 1.3.7rc3 on FreeBSD 12-STABLE. OpenSSL 1.1.1g. All works well. However, when I checked out the latest source and built it (successfully), I was no longer able to connect. I tried it on two separate servers and two different clients (lftp and Transmit) and got the same result.

```
2020-05-07 17:58:09,984 mod_tls/2.9[33279]: TLS/TLS-C requested, starting TLS handshake
2020-05-07 17:58:10,037 mod_tls/2.9[33279]: unable to accept TLS connection: protocol error: 
  (1) error:1427D0EA:SSL routines:construct_stateless_ticket:callback failed
2020-05-07 17:58:10,037 mod_tls/2.9[33279]: TLS/TLS-C negotiation failed on control channel
```

Then I reverted to 1.3.7rc3 and normalcy returned:

```
2020-05-07 17:59:06,975 mod_tls/2.9[40786]: TLS/TLS-C requested, starting TLS handshake
2020-05-07 17:59:07,022 mod_tls/2.9[40786]: client supports secure renegotiations
2020-05-07 17:59:07,022 mod_tls/2.9[40786]: TLSv1.3 connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
2020-05-07 17:59:07,059 mod_tls/2.9[40786]: Protection set to Private
2020-05-07 17:59:07,121 mod_tls/2.9[40786]: TLSv1.3 data connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
```

**Comment by Castaglia** [comment] 2020-05-13 15:48
Could you provide your `proftpd.conf`, please?  And the output from `openssl version -a`?

**Comment by freultwah** [comment] 2020-05-13 18:25
As I said, OpenSSL 1.1.1g.

```
OpenSSL 1.1.1g-freebsd  21 Apr 2020
built on: reproducible build, date unspecified
platform: FreeBSD-amd64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: clang
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines"
Seeding source: os-specific
```

Relevant bits from proftpd.conf:

```
<IfModule mod_tls.c>
  TLSEngine                     on
  TLSLog                        /var/log/proftpd/tls.log
  TLSProtocol                   TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
  TLSCipherSuite                AES128+EECDH:AES128+EDH:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDH+AES256:ECDH+AES128:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA:ECDH+3DES:CAMELLIA256-SHA:CAMELLIA128-SHA:ECDH+3DES:RSA+3DES:ECDHE-RSA-RC4-SHA:RC4-SHA:!aNULL:!MD5
  TLSServerCipherPreference     on
  TLSOptions                    AllowClientRenegotiations NoSessionReuseRequired NoEmptyFragments
  TLSCACertificateFile          /usr/local/etc/proftpd/letsencryptauthorityx3.pem
  TLSRSACertificateFile         /usr/local/etc/dehydrated/certs/XXX/cert.pem
  TLSRSACertificateKeyFile      /usr/local/etc/dehydrated/certs/XXX/privkey.pem
  TLSDHParamFile                /usr/local/etc/proftpd/dh4096.pem
  TLSTimeoutHandshake           30
  TLSVerifyClient               off
  TLSRequired                   no
  RequireValidShell             no
  TLSRenegotiate                ctrl 3600 data 25165824 required off timeout 180
</IfModule>
```

**Comment by freultwah** [comment] 2020-05-15 10:08
I also get tons (OK, 21) of warnings about deprecated declarations in mod_tls.c, and incompatible pointer types, and other stuff, too.

```
/usr/include/openssl/opensslconf.h:147:34: note: expanded from macro 'DEPRECATEDIN_1_1_0'
# define DEPRECATEDIN_1_1_0(f)   DECLARE_DEPRECATED(f)
                                 ^
/usr/include/openssl/opensslconf.h:110:55: note: expanded from macro 'DECLARE_DEPRECATED'
#   define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                                      ^
../modules/mod_tls.c:9646:31: warning: passing 'X509_ALGOR **' (aka 'struct X509_algor_st **') to parameter of type 'const X509_ALGOR **' (aka 'const struct X509_algor_st **') discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
    X509_get0_signature(NULL, &algo, cert);
                              ^~~~~
/usr/include/openssl/x509.h:572:45: note: passing argument to parameter 'palg' here
                         const X509_ALGOR **palg, const X509 *x);
                                            ^
```
Etc.

Related? I don't know, I cannot code, just reporting what Clang warns about.

**Comment by freultwah** [comment] 2020-05-15 13:08
Did some digging, checked out various commits and watched how they behave.

9ecdb16c484939e9a1fcc9aabd272204dc4a7f98

Access to TLS works with Transmit (does not issue HOST), fails with lftp (issues HOST, fails)

lftp (paranoid.log)
```
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "FEAT" 211 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "FEAT" 211 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "CLNT lftp/4.9.1" 200 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "LANG en_US.UTF-8" 200 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "OPTS_UTF8 ON" 200 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "OPTS UTF8 ON" - -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "HOST hullu.lehma.com" 504 -
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:47:10 +0000] "USER xxx" 331 -
```

lftp (tls.log)
```
2020-05-15 15:47:10,850 mod_tls/2.9[63429]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:47:10,863 mod_tls/2.9[63429]: no matching server found for client-sent SNI 'XXX.com', rejecting SSL/TLS connection
2020-05-15 15:47:10,864 mod_tls/2.9[63429]: unable to accept TLS connection: protocol error: 
  (1) error:1422E0EA:SSL routines:final_server_name:callback failed
2020-05-15 15:47:10,864 mod_tls/2.9[63429]: TLS/TLS-C negotiation failed on control channel
```

Transmit (tls.log)
```
2020-05-15 15:47:18,611 mod_tls/2.9[66009]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:47:18,682 mod_tls/2.9[66009]: client supports secure renegotiations
2020-05-15 15:47:18,682 mod_tls/2.9[66009]: TLSv1.3 connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
2020-05-15 15:47:18,712 mod_tls/2.9[66009]: Protection set to Private
2020-05-15 15:47:18,782 mod_tls/2.9[66009]: TLSv1.3 data connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
```

73e872f414cb155e0144f4d1e9d8e34e59a40ea2

Access to TLS does not work at all (Transmit), downgrade to plaintext still works (lftp)

Transmit (tls.log)
```
2020-05-15 15:55:26,197 mod_tls/2.9[78555]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:55:26,267 mod_tls/2.9[78555]: unable to accept TLS connection: protocol error: 
  (1) error:1427D0EA:SSL routines:construct_stateless_ticket:callback failed
2020-05-15 15:55:26,268 mod_tls/2.9[78555]: TLS/TLS-C negotiation failed on control channel
2020-05-15 15:55:26,302 mod_tls/2.9[79210]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:55:26,372 mod_tls/2.9[79210]: unable to accept TLS connection: protocol error: 
  (1) error:1427D0EA:SSL routines:construct_stateless_ticket:callback failed
2020-05-15 15:55:26,373 mod_tls/2.9[79210]: TLS/TLS-C negotiation failed on control channel
```

Starting with e8953672efef6ad4ebb02f25f29ee1ca6a933241, no client that I tried can access the server at all, plaintext or otherwise.

Access dies on FEAT for the plaintext connection:
```
2001:7d0:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx UNKNOWN - [15/May/2020:15:40:11 +0000] "FEAT" 211 -
```

FTPS dies before reaching that point (as it has for some time now):

```
2020-05-15 15:41:20,049 mod_tls/2.9[70319]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:41:20,119 mod_tls/2.9[70319]: unable to accept TLS connection: protocol error: 
  (1) error:1427D0EA:SSL routines:construct_stateless_ticket:callback failed
2020-05-15 15:41:20,119 mod_tls/2.9[70319]: TLS/TLS-C negotiation failed on control channel
2020-05-15 15:41:20,154 mod_tls/2.9[70969]: TLS/TLS-C requested, starting TLS handshake
2020-05-15 15:41:20,224 mod_tls/2.9[70969]: unable to accept TLS connection: protocol error: 
  (1) error:1427D0EA:SSL routines:construct_stateless_ticket:callback failed
2020-05-15 15:41:20,225 mod_tls/2.9[70969]: TLS/TLS-C negotiation failed on control channel
```

**Comment by Castaglia** [comment] 2020-05-23 15:46
I wonder if OpenSSL changed something between 1.1.1c (when I last verified all of this TLSv1.3 fun), and 1.1.1g.

To verify if this behavior is indeed specific to TLSv1.3, can you try using:
```
TLSProtocol TLSv1 TLSv1.1 TLSv1.2
```
in your config, and explicitly _omit_ TLSv1.3 from the protocol version list?

**Comment by Castaglia** [comment] 2020-05-23 16:01
Also, you could add the following to your `<IfModule mod_tls.c>` configuration, to get more details on possible sources of the error?
```
TraceLog /var/log/proftpd/tls.log
Trace tls:20
TLSOptions EnableDiags
```
This enables diagnostic logging of the TLS packets, _and_ details trace logging of mod_tls internals -- the "callback failed" OpenSSL error indicates that one of the callback functions used by `mod_tls` might be failing unexpectedly, in which case the detailed trace logging might help.

**Comment by freultwah** [comment] 2020-05-24 17:56
1. Connecting over TLSv1.2 works well.

2. Log results with tracing turned on: https://pastebin.com/cZKKft5d

**Comment by Castaglia** [comment] 2020-05-24 21:19
Excellent, thank you for the trace logging.  Since you are compiling ProFTPD from source, would you also happen to have the generated `config.h` file, from the source compilation?  It contains the results of the tests that the `configure.sh` script runs, at build-time.  Another piece of this puzzle might be contained in the `config.h` file from your build.

**Comment by Castaglia** [comment] 2020-05-24 21:47
I'm trying to reproduce this behavior locally, using a FreeBSD 12 Vagrant VM.  In particular, I am looking for log messages related to "session ticket keys".  Based on the OpenSSL error message reported, the callback function that `mod_tls` provides, for encrypting session tickets (required by TLSv1.3, but not earlier versions) using a custom key, is failing [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_tls.c#L6554):
```
    if (tls_ticket_keys == NULL) {
      return -1;
    }
```
But why would `tls_ticket_keys` (a list of keys) be `NULL`?

So in my Vagrant VM, I start ProFTPD manually (rather than using some init script) using:
```
$ /usr/local/sbin/proftpd -nd10
```
in order to see any `mod_tls`-related startup messages.  Here's what I found:
```
2020-05-24 21:40:32,459 freebsd12.localdomain proftpd[10831]: mod_tls/2.9: compiled using OpenSSL version 'OpenSSL 1.1.1g  21 Apr 2020' headers, but linked to OpenSSL version 'OpenSSL 1.1.1d-freebsd  10 Sep 2019' library
...
2020-05-24 21:40:32,461 freebsd12.localdomain proftpd[10831] localhost: mod_tls/2.9: generating initial TLS session ticket key
2020-05-24 21:40:32,462 freebsd12.localdomain proftpd[10831] localhost: mod_tls/2.9: scheduling new TLS session ticket key every 3600 secs
```
These look fine -- although the warning about the differences between compile-time OpenSSL version and link-time OpenSSL version is a bit concerning.

Do you see similar log messages, if you start ProFTPD manually using:
```
$ /usr/local/sbin/proftpd -nd10 -c /path/to/proftpd.conf
```

**Comment by freultwah** [comment] 2020-05-25 07:18
Done and done. Pastebin link: https://pastebin.com/cKZqMarr

**Comment by Castaglia** [comment] 2020-05-25 15:16
Very good to know, thank you!  Failure to generate session ticket keys will lead to issues with TLSv1.3, yes. Now to see if we can figure out the cause of this "Resource temporarily unavailable" error in your situation.

**Comment by Castaglia** [comment] 2020-05-25 15:36
According to the FreeBSD [`mlock(2)` man page](https://www.freebsd.org/cgi/man.cgi?query=mlock&sektion=2&manpath=freebsd-release-ports), the "Resource temporarily unavailable" error (`EAGAIN`):
> ERRORS
>     The mlock() system	call will fail if:
>
>     [EPERM]		security.bsd.unprivileged_mlock	is set to 0 and	the
>			        caller is not the super-user.
>
>     [EINVAL]		The address range given	wraps around zero.
>
>     [EAGAIN]		Locking	the indicated range would exceed the system
>			        limit for locked memory.

@freultwah do you have configured system limits on the amount of locked memory?  What does `ulimit -a` show for you?  Also, could you run these `sysctl` commands, to see if perhaps they are relevant?
```
# sysctl -a | grep max_wired
vm.max_wired: 164961

# sysctl -a | grep mlock    
vm.old_mlock: 0
p1003_1b.memlock: 0
p1003_1b.memlock_range: 0
security.bsd.unprivileged_mlock: 1
security.jail.param.allow.mlock: 0
```

**Comment by Castaglia** [comment] 2020-05-25 16:33
@freultwah also, if you get a chance, can you see if [this PR](https://github.com/proftpd/proftpd/pull/1021) addresses the issue for you?

**Comment by freultwah** [comment] 2020-05-25 16:52
I have the ftp user capped at 128 MiB in login.conf, but removing that did nothing. vm.max_wired was 632069 and the mlock values were identical to yours. Applying the patch from PR 1021 did the trick, though. TLSv1.3 works again. Nice! Thank you.

**Comment by Castaglia** [comment] 2020-05-25 16:57
@freultwah do you run ProFTPD in a jailed environment?

**Comment by freultwah** [comment] 2020-05-25 16:59
No, I do not. I do drop its privileges down to the ftp user, but no jails.

**Comment by Castaglia** [comment] 2020-05-25 17:01
OK, thanks for confirming that.  Am trying to get as many details as I can, for documenting this issue for future users.

I'll merge (and backport) the PR, to get this fixed in the master branch.

**Closed** 2020-05-25 17:04 UTC
Labels: backport, bug
